#!/usr/bin/env node
/* update-pricing.js — recompute nightly base rates from the comparable homes in
   config.js and write assets/js/rates.js. Run on a schedule by
   .github/workflows/pricing.yml so prices refresh automatically at set times.

   The math here MUST match assets/js/pricing.js so the cron and live site agree.
   Usage: node scripts/update-pricing.js  (run from the ausable-house/ folder)
*/
const fs = require("fs");
const vm = require("vm");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const ctx = { window: {} };
vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(ROOT, "assets/js/config.js"), "utf8"), ctx);
const S = ctx.window.SITE;
const P = S.pricing || { mode: "fixed" };
const SEASONS = ["winter", "spring", "summer", "fall"];

function summarize(vals, method){
  if(!vals.length) return null;
  const a = vals.slice().sort((x,y)=>x-y);
  if(method === "mean") return a.reduce((s,v)=>s+v,0)/a.length;
  if(method === "trimmedMean" && a.length >= 4){ const t=a.slice(1,-1); return t.reduce((s,v)=>s+v,0)/t.length; }
  const m = Math.floor(a.length/2);
  return a.length % 2 ? a[m] : (a[m-1]+a[m])/2;
}
function computeRate(prop, season){
  if(P.mode !== "comps") return prop.rates[season];
  const [lo,hi] = prop.compBedrooms || [0,99];
  const vals = (P.comps||[]).filter(c=>c.bedrooms>=lo && c.bedrooms<=hi)
                            .map(c=>c.rates && c.rates[season]).filter(v=>typeof v==="number");
  const stat = summarize(vals, P.method);
  if(stat == null) return prop.rates[season];
  let rate = stat * (P.positioning ?? 1);
  const floor = (P.floorRate||{})[prop.id];
  if(typeof floor === "number") rate = Math.max(rate, floor);
  const r = P.roundTo || 1;
  return Math.round(rate / r) * r;
}

const rates = {};
S.properties.forEach(p => {
  rates[p.id] = SEASONS.reduce((o,s)=>{ o[s] = computeRate(p, s); return o; }, {});
});

// deterministic timestamp source so CI diffs are meaningful (UTC date only)
const stamp = (process.env.PRICING_DATE || new Date().toISOString().slice(0,10));
const out =
`/* AUTO-GENERATED by scripts/update-pricing.js — do not edit by hand.
   Nightly base rates derived from the comparable homes in config.js.
   Regenerated on a schedule by .github/workflows/pricing.yml. */
window.SITE_RATES = ${JSON.stringify({ generatedAt: stamp, method: P.method, positioning: P.positioning, rates }, null, 2)};
`;
fs.writeFileSync(path.join(ROOT, "assets/js/rates.js"), out);
console.log("Wrote assets/js/rates.js ("+stamp+")");
S.properties.forEach(p => console.log(" ", p.name, JSON.stringify(rates[p.id])));
