#!/usr/bin/env python3
"""Library expansion seed, 2026-09-08.

Adds ~150 real places across the categories the owner asked for (bars, breweries,
Olympic sites, shops & outfitters incl. The Mountaineer, antiques, leaf-peeping,
fishing guides, boat rentals, ski shops, ski areas, biking, indoor days, events).
Every entry is marked UNVERIFIED with source [G2] until it passes a vetting cycle,
and carries an empty `commentary` field for the owner's colour commentary.
Idempotent: re-running updates entries by id and never duplicates.
"""
import json, pathlib, datetime as dt
ROOT = pathlib.Path(__file__).resolve().parents[1]
P = ROOT / "places.json"
d = json.load(open(P))
TODAY = "2026-09-08"

DRIVE = {"Wilmington":"5–10 min", "Wilmington Notch (NY-86)":"5–10 min south", "Jay":"12 min north", "Upper Jay":"15 min north", "Au Sable Forks":"20 min north",
 "Black Brook / Silver Lake":"20–25 min north", "Lake Placid":"15 min down the road · 13 mi via NY-86", "Lake Placid / Olympic Sports Complex":"25 min via NY-86 & NY-73",
 "Adirondak Loj / High Peaks area":"30 min via Adirondak Loj Rd", "North Elba":"20 min", "Keene":"30 min via NY-9N", "Keene Valley":"40 min via NY-9N & NY-73",
 "Cascade Pass, Route 73":"25 min via Lake Placid", "Saranac Lake":"≈35 min via NY-86", "Ray Brook":"25 min via NY-86", "Bloomingdale":"40 min", "Vermontville":"45 min",
 "Keeseville":"35 min via NY-9N", "Chesterfield / Keeseville":"40 min via NY-9N", "Tupper Lake":"1 h 10 min", "Elizabethtown":"45 min", "Plattsburgh":"55 min", "Paul Smiths":"50 min",
 "Blue Mountain Lake":"1 h 45 min", "Pottersville":"1 h 15 min", "Malone":"1 h 15 min", "Willsboro / Essex":"55 min"}

def E(id, name, cat, area, review, sub="", drive=None, address="", phone="", website=None, links=None, suits=None, season="Year-round (verify seasonal hours)", cost="Verify",
      booking="None", hours="Verify same-day", know="", bestFor=None, meal=None, kids=None, brewery=False, goTo=False, tip="", rainOk=False, flags=None, rank=None, **extra):
    p = {"id":id, "name":name, "category":cat, "subcategory":sub or cat, "area":area, "address":address, "phone":phone, "website":website,
         "websiteKind":"official" if website else None, "rank":rank, "areaRank":None, "rankScope":None, "review":review, "bestFor":bestFor or [], "order":"",
         "knowBefore":know, "occasionPick":None, "signals":{}, "season":season, "hours":hours, "cost":cost, "booking":booking, "access":"Verify",
         "suits":suits or [], "flags":flags or [], "drive":drive or DRIVE.get(area, "Verify"), "photo":None, "links":links or [],
         "source":{"name":"Library seed 2026-09-08 — regional tourism guides, official sites and general knowledge; not yet vetted", "ref":"[G2]", "url":website or ""},
         "verification":{"lastVerified":None, "verifiedBy":"", "method":"", "nextReview":"2026-10-08", "status":"unverified"},
         "status":"active", "commentary":"", "rainOk":rainOk}
    if meal: p["meal"] = meal
    if kids is not None: p["kids"] = kids
    if brewery: p["brewery"] = True
    if goTo: p["goTo"] = True
    if tip: p["tip"] = tip
    p.update(extra); return p

def L(label, url, kind="info"): return {"label":label, "url":url, "kind":kind}
def AT(slug): return L("AllTrails", "https://www.alltrails.com/trail/us/new-york/" + slug, "alltrails")
LP = "Lake Placid"; SL = "Saranac Lake"; WI = "Wilmington"; KV = "Keene Valley"; KE = "Keene"
NEW = []

# ───────────────────────── DINING ─────────────────────────
NEW += [
E("wilderness-inn-wilmington", "Wilderness Inn II", "Dining", WI, "Old-school Adirondack steak-and-seafood house with a log-cabin dining room and a bar that locals have used for decades. The kind of place for prime rib after a Whiteface day.", sub="Classic Adirondack steakhouse", address="5481 NYS Route 86, Wilmington, NY 12997", suits=["families","groups","classic"], meal=["dinner","drinks"], kids=True, cost="$$–$$$", booking="Reservations smart on weekends"),
E("steinhoffs-sportsmans-inn", "Steinhoff's Sportsman's Inn", "Dining", WI, "Unfussy bar and grill on NY-86 with a big Whiteface view from the back, burgers and wings, and a snowmobile-and-ski crowd in winter.", sub="Bar & grill / tavern", address="NYS Route 86, Wilmington, NY 12997", suits=["casual","groups"], meal=["dinner","drinks"], kids=True, cost="$–$$"),
E("rf-mcdougalls-pub", "R.F. McDougall's Pub (at the Hungry Trout)", "Dining", WI, "The Hungry Trout's casual sibling: a proper pub room with burgers, fish and chips and a solid tap list, right above the West Branch. Easier and cheaper than the dining room next door.", sub="Pub / casual", address="5239 NYS Route 86, Wilmington, NY 12997", website="https://hungrytrout.com/", suits=["casual","families","dogs"], meal=["dinner","drinks"], kids=True, cost="$$"),
E("the-candy-man-wilmington", "The Candy Man", "Dining", WI, "Wilmington's own chocolate shop, making candy in the back since the 1970s. Fudge, truffles, chocolate-covered everything and maple treats; a reliable rainy-hour stop with kids.", sub="Chocolate shop / sweets", address="NYS Route 86, Wilmington, NY 12997", website="https://www.candymanonline.com/", suits=["families","sweet"], meal=["dessert"], kids=True, rainOk=True, cost="$"),
E("stewarts-wilmington", "Stewart's Shops — Wilmington", "Essentials", WI, "The North Country institution: fuel, milk, coffee, ice cream by the scoop and the cheapest quick breakfast around. Open early and late.", sub="Convenience / fuel / ice cream", address="NYS Route 86, Wilmington, NY 12997", website="https://www.stewartsshops.com/", suits=["essentials","families"], season="Year-round", cost="$"),
E("adk-cafe-keene", "ADK Café", "Dining", KE, "Locally sourced café cooking in a little house in Keene: breakfast burritos, sandwiches, dinners some nights and a porch. Handy before or after Route 73 hikes.", sub="Café / brunch / local", address="NYS Route 73, Keene, NY 12942", suits=["hikers","brunch","families"], meal=["breakfast","lunch"], kids=True, cost="$–$$"),
E("cedar-run-bakery-market", "Cedar Run Bakery & Market", "Dining", KE, "The trailhead pantry for the High Peaks: fresh bread and pastries, made-to-order sandwiches, soups, take-and-bake dinners and good coffee. Grab trail lunches here on the way to Cascade or Giant.", sub="Bakery / market / lunch", address="NYS Route 73, Keene, NY 12942", website="https://www.cedarrunbakery.com/", suits=["hikers","families","picnic"], meal=["breakfast","lunch"], kids=True, cost="$"),
E("baxter-mountain-tavern", "Baxter Mountain Tavern", "Dining", KE, "Roadside tavern on the Spruce Hill stretch of NY-9N with mountain views, a fireplace, burgers, steaks and a long list of local beer. The natural post-Baxter or post-Hurricane stop.", sub="Tavern / American", address="10050 NYS Route 9N, Keene, NY 12942", website="https://www.baxtermountaintavern.com/", suits=["hikers","groups","families"], meal=["dinner","drinks"], kids=True, cost="$$", booking="Walk in; can be a wait on weekends"),
E("ausable-inn-keene-valley", "Ausable Inn", "Dining", KV, "Keene Valley's village pub-restaurant: pizza, burgers, pasta and a bar full of climbers and hikers swapping stories. Sits a few doors from The Mountaineer.", sub="Pub / pizza / American", address="1809 NYS Route 73, Keene Valley, NY 12943", suits=["hikers","groups","families"], meal=["dinner","drinks"], kids=True, cost="$$"),
E("the-view-mirror-lake-inn", "The View at Mirror Lake Inn", "Dining", LP, "The area's formal dining room: AAA Four Diamond, white tablecloths, a wall of windows over Mirror Lake. Book it for the anniversary dinner, not for a night with toddlers.", sub="Fine dining / lake view", address="77 Mirror Lake Drive, Lake Placid, NY 12946", phone="518-302-3000", website="https://mirrorlakeinn.com/dining/the-view/", suits=["couples","special"], meal=["dinner"], kids=False, cost="$$$$", booking="Reservations required; smart-casual dress"),
E("the-cottage-mirror-lake-inn", "The Cottage (Mirror Lake Inn)", "Dining", LP, "Casual lakeside café and bar across the road from the Inn, with a deck right on Mirror Lake. Sandwiches, salads, nachos and a drink at sunset; one of the best warm-evening seats in town.", sub="Casual / lakeside deck / bar", address="77 Mirror Lake Drive, Lake Placid, NY 12946", website="https://mirrorlakeinn.com/dining/the-cottage/", suits=["couples","casual","sunset"], meal=["lunch","dinner","drinks"], kids=True, cost="$$", booking="No reservations; arrive before sunset for a deck table"),
E("generations-golden-arrow", "Generations Tap & Grill (Golden Arrow)", "Dining", LP, "Hotel restaurant on Main Street with a lake-view dining room and a broad, crowd-pleasing menu. Reliable for a mixed group when the small rooms are full.", sub="American / hotel dining", address="2559 Main Street, Lake Placid, NY 12946", website="https://www.golden-arrow.com/dining/", suits=["families","groups"], meal=["breakfast","dinner","drinks"], kids=True, cost="$$–$$$"),
E("lake-placid-lodge-dining", "Lake Placid Lodge — Artisans & Maggie's Pub", "Dining", LP, "Great Camp atmosphere on the shore of Lake Placid itself: Artisans for a serious dinner, Maggie's Pub for a fireside drink and a simpler plate. A special-occasion drive out Whiteface Inn Lane.", sub="Fine dining / Great Camp pub", address="144 Lodge Way, Lake Placid, NY 12946", website="https://www.lakeplacidlodge.com/", suits=["couples","special"], meal=["dinner","drinks"], kids=False, cost="$$$$", booking="Reservations essential"),
E("kanu-whiteface-lodge", "KANU Restaurant & Lounge (Whiteface Lodge)", "Dining", LP, "Timber-and-stone lodge dining with a big fireplace lounge, cocktails and a menu built for celebrations. A step up in price, matched by the room.", sub="Fine dining / lodge lounge", address="7 Whiteface Inn Lane, Lake Placid, NY 12946", website="https://www.thewhitefacelodge.com/dining/", suits=["couples","special"], meal=["dinner","drinks"], kids=True, cost="$$$–$$$$", booking="Reservations recommended"),
E("breakfast-club-etc", "The Breakfast Club, Etc.", "Dining", LP, "Lake Placid's breakfast institution: huge pancakes, eggs every way, mimosas and a line out the door on weekends. Worth the wait once; go early.", sub="Breakfast / brunch", address="2490 Main Street, Lake Placid, NY 12946", website="https://www.breakfastclubetc.com/", suits=["families","brunch"], meal=["breakfast"], kids=True, cost="$–$$", booking="No reservations; weekend waits"),
E("chair-6-lake-placid", "Chair 6", "Dining", LP, "Small, chef-run breakfast-and-lunch room on Sentinel Road with inventive specials and very good baked goods. Quieter than Main Street.", sub="Breakfast / lunch / bakery", address="5993 Sentinel Road, Lake Placid, NY 12946", suits=["brunch","couples"], meal=["breakfast","lunch"], kids=True, cost="$–$$"),
E("origin-coffee-lake-placid", "Origin Coffee Co.", "Dining", LP, "Specialty coffee with a chef-driven breakfast and lunch menu and rotating local art. Locations in Lake Placid and Saranac Lake; the one to pick for a good flat white.", sub="Coffee / café", address="Main Street, Lake Placid, NY 12946", website="https://www.origincoffeeadk.com/", suits=["coffee","brunch"], meal=["breakfast","lunch"], kids=True, rainOk=True, cost="$"),
E("bluesberry-bakery", "Bluesberry Bakery", "Dining", LP, "Tiny Main Street bakery with scones, croissants, cookies and pies that sell out. Grab a box for the cabin.", sub="Bakery", address="2436 Main Street, Lake Placid, NY 12946", suits=["sweet","coffee"], meal=["breakfast","dessert"], kids=True, cost="$"),
E("saranac-sourdough", "Saranac Sourdough", "Dining", LP, "Bread-first bakery-café on the Saranac Avenue strip: sourdough loaves, big sandwiches and soups for a trail day. Handy on the way west.", sub="Bakery / sandwiches", address="Saranac Avenue, Lake Placid, NY 12946", suits=["picnic","hikers"], meal=["breakfast","lunch"], kids=True, cost="$"),
E("simply-gourmet-lake-placid", "Simply Gourmet", "Dining", LP, "The famous 46-sandwich menu, one named for each High Peak. Order ahead, drive to a trailhead or the beach.", sub="Sandwiches / take-out", address="1983 Saranac Avenue, Lake Placid, NY 12946", website="https://www.simplygourmetlakeplacid.com/", suits=["picnic","hikers","families"], meal=["lunch"], kids=True, cost="$"),
E("liquids-and-solids", "Liquids & Solids at the Handlebar", "Dining", LP, "Creative small plates, nose-to-tail specials, natural wine and serious cocktails in a former bike shop. The most interesting dinner in town for adults; not the place for a fussy eater.", sub="Creative small plates / cocktails", address="6115 Sentinel Road, Lake Placid, NY 12946", website="https://www.liquidsandsolids.com/", suits=["couples","foodies"], meal=["dinner","drinks"], kids=False, cost="$$$", booking="Reservations recommended"),
E("nicolas-on-main", "Nicola's on Main", "Dining", LP, "Wood-fired pizza, pasta and Italian-Mediterranean plates on Main Street from the family behind Caffè Rustica. A dependable middle ground for groups.", sub="Italian / pizza", address="2589 Main Street, Lake Placid, NY 12946", suits=["families","groups"], meal=["dinner"], kids=True, cost="$$–$$$"),
E("delta-blue-lake-placid", "Delta Blue", "Dining", LP, "Cajun-Creole cooking and live blues on Main Street; gumbo, po'boys and a bar that stays lively late.", sub="Cajun / live music bar", address="Main Street, Lake Placid, NY 12946", suits=["nightlife","groups"], meal=["dinner","drinks"], kids=True, cost="$$"),
E("pickled-pig-lake-placid", "The Pickled Pig", "Dining", LP, "Barbecue and a bourbon-heavy bar on Saranac Avenue: brisket, ribs, pulled pork and a smoker out back. The casual alternative when Smoke Signals has a wait.", sub="BBQ / bar", address="Saranac Avenue, Lake Placid, NY 12946", suits=["families","groups","casual"], meal=["dinner","drinks"], kids=True, cost="$$"),
E("dack-shack", "The Dack Shack", "Dining", LP, "Counter-service burgers, wings, tacos and beer with a big patio on Saranac Avenue. Loud, cheap, kid-proof.", sub="Casual / patio", address="Saranac Avenue, Lake Placid, NY 12946", suits=["families","casual"], meal=["lunch","dinner"], kids=True, cost="$"),
E("emmas-lake-placid-creamery", "Emma's Lake Placid Creamery", "Dining", LP, "Main Street ice cream window with dozens of flavours and a queue on summer nights; the after-dinner walk-to.", sub="Ice cream", address="Main Street, Lake Placid, NY 12946", suits=["families","sweet"], meal=["dessert"], kids=True, season="Seasonal (spring–fall; verify)", cost="$"),
E("green-goddess-market", "Green Goddess Natural Market", "Dining", LP, "Natural-foods market with a smoothie and salad bar and a hot case: the healthy lunch and the place for special diets. Also a good grocery top-up.", sub="Natural market / café", address="2051 Saranac Avenue, Lake Placid, NY 12946", website="https://www.greengoddessfoods.com/", suits=["healthy","essentials"], meal=["lunch"], kids=True, cost="$–$$"),
E("left-bank-cafe", "Left Bank Café", "Dining", SL, "French-leaning bistro in downtown Saranac Lake: crêpes, tartines, quiche and a short wine list. Reopened as a proper bistro; an unexpected pleasure.", sub="French bistro / café", address="36 Broadway, Saranac Lake, NY 12983", website="https://www.leftbankcafeadk.com/", suits=["couples","brunch"], meal=["breakfast","lunch","dinner"], kids=True, cost="$$"),
E("fiddlehead-bistro", "Fiddlehead Bistro", "Dining", SL, "Farm-to-table bistro on Broadway with a small, changing menu and a good bar. Saranac Lake's date-night room.", sub="Farm-to-table bistro", address="Broadway, Saranac Lake, NY 12983", suits=["couples","foodies"], meal=["dinner"], kids=False, cost="$$$", booking="Reservations recommended"),
E("campfire-hotel-saranac", "Campfire Adirondack Grill + Bar (Hotel Saranac)", "Dining", SL, "The restored 1927 Hotel Saranac's grill: wood-fired plates, a handsome bar and the Great Hall upstairs for a drink under the painted ceiling.", sub="Grill / hotel bar", address="100 Main Street, Saranac Lake, NY 12983", website="https://hotelsaranac.com/", suits=["couples","groups"], meal=["breakfast","dinner","drinks"], kids=True, cost="$$–$$$"),
E("lakeview-deli", "Lakeview Deli", "Dining", SL, "Beloved sandwich shop across from Lake Flower: overstuffed subs, wraps and salads, best eaten at the picnic tables by the water.", sub="Deli / sandwiches", address="102 River Street, Saranac Lake, NY 12983", suits=["picnic","families"], meal=["lunch"], kids=True, cost="$"),
E("casa-del-sol", "Casa del Sol", "Dining", SL, "Long-running Mexican cantina with a shaded patio and strong margaritas; a Saranac Lake summer fixture.", sub="Mexican", address="154 Lake Flower Avenue, Saranac Lake, NY 12983", suits=["families","groups"], meal=["dinner","drinks"], kids=True, cost="$$"),
E("nonna-fina", "Nonna Fina", "Dining", SL, "Family Italian on Lake Flower Avenue: red-sauce classics, big portions and a warm room.", sub="Italian-American", address="Lake Flower Avenue, Saranac Lake, NY 12983", suits=["families","groups"], meal=["dinner"], kids=True, cost="$$"),
E("noris-village-market", "Nori's Village Market", "Dining", SL, "The Adirondacks' biggest natural-and-local grocer, with a deli and prepared foods; stock the cabin here if you are coming from the west.", sub="Natural market / deli", address="65 Main Street, Saranac Lake, NY 12983", website="https://www.norisvillagemarket.com/", suits=["essentials","healthy"], meal=["lunch"], kids=True, cost="$–$$"),
E("mountain-mist-custard", "Mountain Mist Custard", "Dining", SL, "Roadside frozen-custard stand on Lake Flower with picnic tables at the water and a paddleboat view. Summer only.", sub="Frozen custard", address="260 Lake Flower Avenue, Saranac Lake, NY 12983", suits=["families","sweet"], meal=["dessert"], kids=True, season="Summer (verify)", cost="$"),
E("origin-coffee-saranac-lake", "Origin Coffee Co. — Saranac Lake", "Dining", SL, "The Saranac Lake outpost of the specialty roaster-café: breakfast plates, pastries and the best espresso in the village.", sub="Coffee / café", address="Broadway, Saranac Lake, NY 12983", website="https://www.origincoffeeadk.com/", suits=["coffee","brunch"], meal=["breakfast","lunch"], kids=True, rainOk=True, cost="$"),
E("rivermede-farm-market", "Rivermede Farm Market", "Farms & local life", KV, "Working farm and farm store in Keene Valley: vegetables, eggs, maple, baked goods and flowers. A pretty stop on the way back from a High Peaks day.", sub="Farm store", address="NYS Route 73, Keene Valley, NY 12943", suits=["families","food"], season="Seasonal (verify)", cost="$"),
E("mace-chasm-farm", "Mace Chasm Farm", "Farms & local life", "Keeseville", "Pasture-raised meats, a butcher counter and a farm store minutes from Ausable Brewing; the two make a natural pairing.", sub="Farm store / butcher", address="Mace Chasm Road, Keeseville, NY 12944", suits=["food","families"], cost="$$"),
E("north-country-creamery", "North Country Creamery (Clover Mead Café)", "Farms & local life", "Keeseville", "Grass-fed dairy with yogurt, cheese and a small farm café; combine with Ausable Chasm for a Keeseville day.", sub="Dairy / farm café", address="Keeseville, NY 12944", suits=["families","food"], meal=["breakfast","lunch"], cost="$"),
E("saranac-lake-farmers-market", "Saranac Lake Farmers' Market", "Farms & local life", SL, "Saturday-morning market at Riverside Park with produce, cheese, bread, maple and music in summer. Pairs with the carousel two blocks away.", sub="Farmers' market", address="Riverside Park, Saranac Lake, NY 12983", suits=["families","food"], season="Saturdays, late spring–fall (verify schedule)", cost="Free entry"),
]

# ───────────────────────── BARS & NIGHTLIFE ─────────────────────────
NEW += [
E("cloudsplitter-rooftop-bar", "Cloudsplitter Rooftop Bar (Grand Adirondack Hotel)", "Bars & nightlife", LP, "The rooftop bar in town: cocktails, small plates and a 360° look at the High Peaks and Mirror Lake from above Main Street. Reopens each May; the place for a summer sunset drink and Fourth-of-July fireworks.", sub="Rooftop cocktail bar", address="2520 Main Street, Lake Placid, NY 12946", website="https://www.marcyrestaurant.com/cloudsplitter-rooftop-bar/", suits=["couples","groups","sunset"], meal=["drinks"], kids=False, season="Mid-May to fall, weather permitting (verify)", hours="Roughly 2–10 pm in season (verify)", cost="$$–$$$", goTo=True, tip="Owner go-to for a summer evening. Go up an hour before sunset.", flags=["rooftop"]),
E("the-deck-high-peaks-resort", "The Deck at High Peaks Resort", "Bars & nightlife", LP, "Open-air deck above Main Street looking straight down Mirror Lake; drinks, casual food and live music some evenings.", sub="Lakeview deck bar", address="2384 Saranac Avenue, Lake Placid, NY 12946", website="https://www.highpeaksresort.com/", suits=["groups","sunset"], meal=["drinks","dinner"], kids=True, season="Summer–fall (verify)", cost="$$"),
E("zig-zags-pub", "Zig Zags Pub", "Bars & nightlife", LP, "Lake Placid's dive-bar-with-heart: darts, live music, cheap pints and a local crowd. The late stop.", sub="Pub / live music", address="134 Main Street, Lake Placid, NY 12946", suits=["nightlife","groups"], meal=["drinks"], kids=False, cost="$"),
E("wiseguys-sports-bar", "Wiseguys Sports Bar & Grill", "Bars & nightlife", LP, "Screens, wings and pitchers on Saranac Avenue; the game-day bar, easy with a group.", sub="Sports bar", address="Saranac Avenue, Lake Placid, NY 12946", suits=["groups","casual"], meal=["drinks","dinner"], kids=True, cost="$–$$"),
E("roomers-lake-placid", "Roomers", "Bars & nightlife", LP, "Main Street bar and nightclub that fills after 10 pm in season; DJs, dancing, not for quiet conversation.", sub="Bar / nightclub", address="Main Street, Lake Placid, NY 12946", suits=["nightlife"], meal=["drinks"], kids=False, cost="$$"),
E("dancing-bears-golden-arrow", "Dancing Bears Restaurant & Lounge (Golden Arrow)", "Bars & nightlife", LP, "Hotel lounge and bar on Main Street with a lake-view deck; a calmer drink than the pubs, with food until late.", sub="Hotel lounge / deck", address="2559 Main Street, Lake Placid, NY 12946", website="https://www.golden-arrow.com/", suits=["couples","groups"], meal=["drinks","dinner"], kids=True, cost="$$"),
E("players-sports-bar", "Player's Sports Bar & Grill", "Bars & nightlife", LP, "Pool tables, pub food and a Saranac Avenue location away from the Main Street crowds.", sub="Sports bar / pool", address="Saranac Avenue, Lake Placid, NY 12946", suits=["groups","casual"], meal=["drinks"], kids=True, cost="$"),
E("great-hall-bar-hotel-saranac", "Great Hall Bar (Hotel Saranac)", "Bars & nightlife", SL, "Cocktails under the restored painted ceiling of a 1927 grand hotel; the most elegant drink in Saranac Lake.", sub="Hotel bar / cocktails", address="100 Main Street, Saranac Lake, NY 12983", website="https://hotelsaranac.com/", suits=["couples"], meal=["drinks"], kids=False, cost="$$–$$$"),
E("the-waterhole-saranac-lake", "The Waterhole", "Bars & nightlife", SL, "Saranac Lake's music venue and bar since forever: touring bands upstairs, a raucous downstairs, a summer concert series. Check the calendar.", sub="Music venue / bar", address="48 Main Street, Saranac Lake, NY 12983", website="https://www.saranacwaterhole.com/", suits=["nightlife","music"], meal=["drinks"], kids=False, cost="$–$$ plus tickets"),
E("downhill-grill-saranac-lake", "Downhill Grill", "Bars & nightlife", SL, "Neighbourhood bar-restaurant on Broadway with a deck, tacos and a big beer list; where locals actually go.", sub="Bar & grill", address="Broadway, Saranac Lake, NY 12983", suits=["casual","groups"], meal=["drinks","dinner"], kids=True, cost="$$"),
E("recovery-lounge-upper-jay", "Recovery Lounge (Upper Jay Art Center)", "Bars & nightlife", "Upper Jay", "Concerts, theatre and cabaret in a former car dealership, with a bar. Small, odd and wonderful; check the season's programme.", sub="Arts venue / bar", address="12198 NYS Route 9N, Upper Jay, NY 12987", website="https://www.upperjayartcenter.org/", suits=["culture","nightlife"], meal=["drinks"], kids=True, cost="Tickets vary", rainOk=True),
]

# ───────────────────────── BREWERIES, CIDER & SPIRITS ─────────────────────────
NEW += [
E("blue-line-brewery", "Blue Line Brewery", "Breweries, cider & spirits", SL, "Saranac Lake's first modern brewery, in a converted car wash on Lake Flower Avenue; a broad tap list and a low-key taproom.", sub="Brewery taproom", address="555 Lake Flower Avenue, Saranac Lake, NY 12983", website="https://www.bluelinebrew.com/", suits=["breweries","groups"], meal=["drinks"], kids=True, brewery=True, cost="$"),
E("ray-brook-brewhouse", "Ray Brook Brewhouse", "Breweries, cider & spirits", "Ray Brook", "Roadside brewpub on NY-86 between Lake Placid and Saranac Lake with a long list of its own beers, pub food and a deck. An easy stop on the way home from the west.", sub="Brewpub", address="Route 86, Ray Brook, NY 12977", website="https://www.raybrookbrewhouse.com/", suits=["breweries","families","groups"], meal=["dinner","drinks"], kids=True, brewery=True, cost="$$"),
E("hex-and-hop-brewing", "Hex & Hop Brewing", "Breweries, cider & spirits", "Bloomingdale", "Small honey-forward brewery on a Bloomingdale side road with a big lawn and food trucks in summer; worth the detour on a Bloomingdale Bog day.", sub="Farm brewery", address="Bloomingdale, NY 12913", suits=["breweries","families","quiet"], meal=["drinks"], kids=True, brewery=True, season="Seasonal hours (verify)", cost="$"),
E("raquette-river-brewing", "Raquette River Brewing", "Breweries, cider & spirits", "Tupper Lake", "Tupper Lake brewery with a live-edge bar, a patio of Adirondack chairs and rotating food trucks; combine with The Wild Center.", sub="Brewery taproom", address="11 Balsam Street, Tupper Lake, NY 12986", website="https://www.raquetteriverbrewing.com/", suits=["breweries","families"], meal=["drinks"], kids=True, brewery=True, cost="$"),
E("main-street-tasting-rooms-lake-placid", "Main Street tasting rooms (Prison City · The Boat · Raquette River)", "Breweries, cider & spirits", LP, "Three satellite tasting rooms from upstate breweries along Main Street let you do a walking beer tour without a car. Names and openings change; check the current list.", sub="Tasting rooms", address="Main Street, Lake Placid, NY 12946", website="https://www.lakeplacid.com/do/dining/breweries", suits=["breweries","groups"], meal=["drinks"], kids=False, brewery=True, cost="$"),
E("high-peaks-distilling", "High Peaks Distilling (Lake Placid Spirits)", "Breweries, cider & spirits", LP, "Small-batch gin, vodka and whiskey distilled in Lake Placid, with a tasting room and cocktails. The bottle to take home.", sub="Craft distillery", address="Lake Placid, NY 12946", website="https://www.lakeplacidspirits.com/", suits=["couples","groups"], meal=["drinks"], kids=False, cost="$$"),
E("adirondack-beer-trail", "Adirondack Craft Beverage Trail", "Breweries, cider & spirits", "Lake Placid / Ray Brook / Saranac Lake", "The regional passport programme linking breweries, cideries and distilleries across the Park; good for planning a designated-driver day.", sub="Trail / passport", website="https://visitadirondacks.com/what-to-do/breweries-distilleries", suits=["breweries"], meal=["drinks"], kids=False, brewery=True, cost="Free", drive="Varies"),
]

# ───────────────────────── OLYMPIC SITES ─────────────────────────
NEW += [
E("olympic-center-herb-brooks-arena", "Olympic Center & Herb Brooks Arena", "Olympic sites", LP, "Where the 1980 'Miracle on Ice' happened. Guided tours take you into the 1980 rink and the 1932 arena; public skating, hockey tournaments and figure-skating shows fill the calendar. Combine with the Olympic Museum next door.", sub="Arena / tours", address="2634 Main Street, Lake Placid, NY 12946", website="https://lakeplacidlegacysites.com/", suits=["families","culture","rain"], rainOk=True, cost="Tour fee (verify)", booking="Tours on a schedule; check the day's events"),
E("bobsled-experience-mt-van-hoevenberg", "Bobsled Experience at Mt Van Hoevenberg", "Olympic sites", "Lake Placid / Olympic Sports Complex", "Ride a real bobsled with a professional driver and brakeman from the half-mile start: on ice in winter, on wheels down the concrete track in summer, up to about 50 mph through the Olympic turns. The signature Lake Placid thrill.", sub="Bobsled ride", address="220 Bobsled Run Lane, Lake Placid, NY 12946", website="https://mtvanhoevenberg.com/todo/bobsled-experience/", suits=["thrill","teens","adults"], cost="$$$ per rider (verify)", booking="Reserve ahead; age, height and weight limits apply", season="Winter on ice; summer on wheels (verify dates)"),
E("skeleton-experience-mt-van-hoevenberg", "Skeleton Experience at Mt Van Hoevenberg", "Olympic sites", "Lake Placid / Olympic Sports Complex", "Head-first, solo, from a lower start on the sliding track after a briefing. Rarer than the bobsled and genuinely hair-raising.", sub="Skeleton ride", address="220 Bobsled Run Lane, Lake Placid, NY 12946", website="https://mtvanhoevenberg.com/", suits=["thrill","adults"], cost="$$$ (verify)", booking="Reserve ahead; strict limits", season="Winter (verify)"),
E("sheffield-speed-skating-oval", "James C. Sheffield Speed Skating Oval", "Olympic sites", LP, "The outdoor oval in front of the high school where Eric Heiden won five golds in 1980. Public skating under the lights in winter; a lovely, cheap evening with kids.", sub="Outdoor skating", address="2634 Main Street, Lake Placid, NY 12946", website="https://lakeplacidlegacysites.com/winter/", suits=["families","winter"], cost="$ admission + rentals (verify)", season="Winter, weather permitting"),
E("olympic-jumping-complex-visit", "Olympic Jumping Complex: tower, zipline & aerials", "Olympic sites", LP, "Beyond the Skyride: the glass elevator to the top of the 120-metre jump, a zipline off the 90-metre tower, and summer freestyle-aerial shows where athletes flip into the pool. Watch for training days.", sub="Ski jumps", address="5486 Cascade Road, Lake Placid, NY 12946", website="https://lakeplacidlegacysites.com/", suits=["families","thrill","sightseeing"], cost="Admission (verify)", season="Year-round; zipline seasonal"),
E("mt-van-hoevenberg-lodge-biathlon", "Mt Van Hoevenberg: Mountain Pass Lodge, biathlon & Nordic", "Olympic sites", "Lake Placid / Olympic Sports Complex", "The 1980 cross-country and biathlon venue rebuilt for 2023's World University Games: 50 km of trails with snowmaking, a biathlon range where you can try shooting, a café and the indoor climbing wall. The winter hub.", sub="Nordic centre", address="220 Bobsled Run Lane, Lake Placid, NY 12946", website="https://mtvanhoevenberg.com/", suits=["winter","families","active"], cost="Trail pass / rentals (verify)", rainOk=True),
E("legacy-sites-passport", "Olympic Legacy Sites Passport", "Olympic sites", LP, "One ticket that bundles the Olympic Museum, Jumping Complex, Mt Van Hoevenberg and the Whiteface Cloudsplitter Gondola over several days. Usually cheaper than three separate tickets for a family.", sub="Multi-venue pass", website="https://lakeplacidlegacysites.com/", suits=["families","value"], cost="Pass price (verify)", booking="Buy online; check which venues are open in your season"),
E("watch-a-world-cup", "Watch a live competition", "Olympic sites", LP, "Lake Placid hosts World Cup bobsled, skeleton and luge, ski-jumping, biathlon and Nordic events, plus the Empire State Winter Games and summer aerials. Spectating is cheap or free and unforgettable; the calendar drives hotel prices, so book early.", sub="Spectator events", website="https://lakeplacidlegacysites.com/events/", suits=["families","winter","culture"], cost="Often free or small fee", season="Mostly December–March; summer aerials"),
E("lake-placid-horse-show-grounds", "Lake Placid Horse Show Grounds", "Events & festivals", LP, "Two weeks of top-level show jumping each late June and early July, free to watch from the rail, with food vendors and a shaded lawn.", sub="Horse shows", address="5514 Cascade Road, Lake Placid, NY 12946", website="https://www.lakeplacidhorseshow.com/", suits=["families","culture"], cost="Free admission (verify)", season="Late June – early July"),
]

# ───────────────────────── EVENTS & FESTIVALS ─────────────────────────
NEW += [
E("ironman-lake-placid", "Ironman Lake Placid", "Events & festivals", LP, "One of the oldest Ironman races in North America, late July: swim in Mirror Lake, bike loops through Wilmington on NY-86 (our road), run to the Olympic Oval finish. Electric to watch, and traffic control affects Wilmington all day.", sub="Triathlon", website="https://www.ironman.com/im-lake-placid", suits=["culture","active"], cost="Free to watch", season="Late July", know="Expect road closures and lane restrictions on NY-86 through Wilmington on race day."),
E("saranac-lake-winter-carnival", "Saranac Lake Winter Carnival", "Events & festivals", SL, "The oldest winter carnival in the eastern US: an Ice Palace built from lake ice, parades, fireworks, ski races and a week of small-town joy every February.", sub="Winter festival", website="https://www.saranaclakewintercarnival.com/", suits=["families","winter","culture"], cost="Mostly free", season="Early–mid February"),
E("empire-state-winter-games", "Empire State Winter Games", "Events & festivals", LP, "Thousands of amateur athletes across the Olympic venues over a long weekend in early February; free spectating at everything from luge to figure skating.", sub="Multi-sport games", website="https://www.empirestatewintergames.com/", suits=["families","winter"], cost="Free to watch", season="Early February"),
E("holiday-village-stroll", "Lake Placid Holiday Village Stroll", "Events & festivals", LP, "First weekend of December: lights, carolers, a tree lighting, open houses along Main Street and horse-drawn wagon rides. Small-town Christmas at its best.", sub="Holiday festival", website="https://www.lakeplacid.com/", suits=["families","winter"], cost="Free", season="Early December"),
E("songs-at-mirror-lake", "Songs at Mirror Lake", "Events & festivals", LP, "Free Wednesday-evening concerts at Mid's Park on Mirror Lake through the summer; bring a blanket and an ice cream from Emma's.", sub="Free concert series", website="https://www.lakeplacidarts.org/", suits=["families","quiet"], cost="Free", season="Summer Wednesdays (verify)"),
E("lake-placid-sinfonietta", "Lake Placid Sinfonietta", "Events & festivals", LP, "The village's professional summer chamber orchestra: Sunday concerts at the Lake Placid Center for the Arts and free Wednesday nights in Mid's Park.", sub="Summer orchestra", website="https://www.lakeplacidsinfonietta.org/", suits=["culture","quiet"], cost="Free outdoors; tickets indoors", season="July–August"),
E("whiteface-uphill-bike-race", "Whiteface Mountain Uphill Bike Race", "Events & festivals", WI, "Riders race the Veterans' Memorial Highway to the summit each June; a dramatic morning to watch from the toll house or the top.", sub="Cycling race", website="https://www.whitefaceregion.com/events", suits=["active","culture"], cost="Free to watch", season="June"),
E("adirondack-mountaineering-festival", "Adirondack International Mountaineering Festival (The Mountaineer)", "Events & festivals", KV, "The Mountaineer's January ice-climbing festival brings guides and athletes to Keene Valley for clinics and slideshows; its March Backcountry Ski Festival is the sequel.", sub="Climbing festival", website="https://mountaineer.com/", suits=["active","winter"], cost="Clinic fees; talks often free", season="January (ice) and March (ski)"),
E("flaming-leaves-oktoberfest", "Fall festivals: Flaming Leaves & Oktoberfest weekends", "Events & festivals", LP, "Autumn weekends bring an Oktoberfest at the ski jumps or Whiteface with beer, brats and foliage; names and venues change year to year, so check the region's calendar before promising anyone.", sub="Fall festival", website="https://www.lakeplacid.com/events", suits=["families","food"], cost="Admission varies", season="Late September – mid-October"),
]

# ───────────────────────── SHOPS & OUTFITTERS ─────────────────────────
NEW += [
E("the-mountaineer-keene-valley", "The Mountaineer", "Shops & outfitters", KV, "The great Adirondack gear store, in a hand-built wooden shop in Keene Valley since 1975. Climbing, backcountry ski, fly-fishing, trail-running and hiking kit chosen by people who use it, plus maps, guidebooks and the best trail advice in the Park. Worth the drive even if you buy only socks.", sub="Outdoor specialty store", address="1866 NYS Route 73, Keene Valley, NY 12943", phone="518-576-2281", website="https://mountaineer.com/", links=[L("Online store","https://store.mountaineer.com/")], suits=["hikers","shopping","rain"], rainOk=True, cost="$$–$$$", goTo=True, tip="Ask them about conditions before any High Peaks day; they know."),
E("lake-placid-ski-and-board", "Lake Placid Ski & Board", "Shops & outfitters", LP, "The full-service ski shop on Main Street: rental fleet, expert boot fitting and a Wintersteiger tuning room. Rent here the evening before a Whiteface day and skip the mountain queue.", sub="Ski shop / rentals / tuning", address="2532 Main Street, Lake Placid, NY 12946", phone="518-523-7245", website="https://www.lakeplacidskiandboard.com/", suits=["winter","shopping"], cost="Rentals $$ (verify)", season="Winter focus; open year-round"),
E("high-peaks-cyclery", "High Peaks Cyclery", "Shops & outfitters", LP, "Bikes, Nordic skis, snowshoes and camping gear with rentals across the seasons; also runs guided rides and rents cross-country packages for Mt Van Hoevenberg.", sub="Bike & Nordic shop / rentals", address="2733 Main Street, Lake Placid, NY 12946", website="https://www.highpeakscyclery.com/", suits=["biking","winter","shopping"], cost="Rentals $$ (verify)"),
E("placid-planet-bicycles", "Placid Planet Bicycles", "Shops & outfitters", LP, "Bike shop and rental on Saranac Avenue with mountain, road and e-bikes, plus ski tuning and waxing in winter.", sub="Bike shop / rentals / ski tuning", address="2242 Saranac Avenue, Lake Placid, NY 12946", website="https://www.placidplanetbicycles.com/", suits=["biking","winter"], cost="Rentals $$ (verify)"),
E("cunninghams-ski-barn-lake-placid", "Cunningham's Ski Barn", "Shops & outfitters", LP, "Long-standing ski and snowboard shop on Main Street with rentals, demos and end-of-season deals.", sub="Ski shop / rentals", address="Main Street, Lake Placid, NY 12946", website="https://www.cunninghamsskibarn.com/", suits=["winter","shopping"], cost="Rentals $$ (verify)"),
E("whiteface-rental-shop", "Whiteface Mountain rental & repair shop", "Shops & outfitters", WI, "On-mountain rentals, lessons and tuning at the base lodge; convenient, but book online and expect a queue on holiday mornings.", sub="On-mountain rentals", address="5021 NYS Route 86, Wilmington, NY 12997", website="https://whiteface.com/", suits=["winter","families"], cost="Rentals $$–$$$ (verify)", season="Ski season"),
E("ems-lake-placid", "Eastern Mountain Sports — Lake Placid", "Shops & outfitters", LP, "Chain outfitter on Main Street with a deep selection of hiking, camping and winter gear; open late, good for the forgotten rain shell.", sub="Outdoor retailer", address="2453 Main Street, Lake Placid, NY 12946", website="https://www.ems.com/", suits=["hikers","shopping","rain"], rainOk=True, cost="$$"),
E("maui-north-lake-placid", "Maui North", "Shops & outfitters", LP, "Ski, snowboard and paddleboard shop with a surf-shop attitude on Main Street; rentals, apparel and demos.", sub="Ski / board / SUP shop", address="Main Street, Lake Placid, NY 12946", website="https://www.mauinorth.net/", suits=["winter","water","shopping"], cost="$$"),
E("leepoff-cycles-wilmington", "Leepoff Cycles", "Shops & outfitters", WI, "Wilmington's own bike shop, steps from the Flume and Hardy Road trails: rentals, repairs and the local word on which trails are dry.", sub="Bike shop / rentals", address="NYS Route 86, Wilmington, NY 12997", suits=["biking"], cost="Rentals $$ (verify)", season="Spring–fall (verify)"),
E("human-power-planet-earth", "Human Power Planet Earth", "Shops & outfitters", SL, "Saranac Lake's bike shop, near the Adirondack Rail Trail, with rentals and repairs.", sub="Bike shop / rentals", address="Saranac Lake, NY 12983", suits=["biking"], cost="Rentals $$ (verify)"),
E("st-regis-canoe-outfitters", "St. Regis Canoe Outfitters", "Shops & outfitters", SL, "The paddling outfitter for the Saranac chain and the St. Regis Canoe Area: canoe and kayak rentals, shuttles, guided trips and a shop full of maps. Start any multi-lake day here.", sub="Paddling outfitter", address="73 Dorsey Street, Saranac Lake, NY 12983", website="https://www.canoeoutfitters.com/", suits=["water","families","active"], cost="Rentals $$ (verify)", season="Spring–fall"),
E("adirondack-lakes-and-trails-outfitters", "Adirondack Lakes & Trails Outfitters", "Shops & outfitters", SL, "Kayak, canoe and paddleboard rentals plus gear and guided paddles from Saranac Lake.", sub="Paddling outfitter", address="541 Lake Flower Avenue, Saranac Lake, NY 12983", website="https://www.adirondackoutfitters.com/", suits=["water","families"], cost="Rentals $$ (verify)", season="Spring–fall"),
E("bookstore-plus", "The Bookstore Plus", "Shops & outfitters", LP, "Independent bookshop on Main Street with a serious Adirondack section, kids' books and puzzles; a rainy-afternoon anchor.", sub="Bookshop", address="2491 Main Street, Lake Placid, NY 12946", website="https://www.thebookstoreplus.com/", suits=["rain","families","culture"], rainOk=True, cost="$"),
E("ruthies-run", "Ruthie's Run", "Shops & outfitters", LP, "Main Street gift shop for Adirondack-y things: Woolrich, moose everything, candles, cabin décor.", sub="Gifts / cabin décor", address="Main Street, Lake Placid, NY 12946", suits=["shopping","rain"], rainOk=True, cost="$$"),
E("adirondack-popcorn-co", "Adirondack Popcorn Co.", "Shops & outfitters", LP, "Small-batch popcorn in dozens of flavours on Main Street; the kids' souvenir.", sub="Snacks / gifts", address="Main Street, Lake Placid, NY 12946", suits=["families","sweet"], cost="$"),
E("the-birch-store", "The Birch Store", "Shops & outfitters", KV, "Keene Valley's stylish general store: clothing, jewellery, home goods and gifts with taste. Pair with The Mountaineer across the road.", sub="Boutique / gifts", address="1778 NYS Route 73, Keene Valley, NY 12943", website="https://www.thebirchstore.com/", suits=["shopping","rain"], rainOk=True, cost="$$–$$$"),
E("dartbrook-rustic-goods", "Dartbrook Rustic Goods", "Shops & outfitters", KE, "Adirondack Great Camp style for the home: rustic furniture, antiques, lighting and textiles in a barn on Route 73 in Keene.", sub="Rustic furniture / décor", address="2496 NYS Route 73, Keene, NY 12942", website="https://www.dartbrookrustic.com/", suits=["shopping","antiques"], rainOk=True, cost="$$$"),
E("young-studio-gallery-jay", "Young's Studio & Gallery", "Shops & outfitters", "Jay", "Stoneware pottery made on site since the 1970s, plus regional art, in a gallery by the Jay covered bridge.", sub="Pottery / gallery", address="NYS Route 86, Jay, NY 12941", website="https://www.youngsstudioandgallery.com/", suits=["shopping","culture"], rainOk=True, cost="$$"),
E("adirondack-store-lake-placid", "The Adirondack Store", "Shops & outfitters", LP, "Rustic home goods, balsam pillows, pack baskets and gifts in the Adirondack style; the shop for outfitting a cabin.", sub="Home goods / gifts", address="2024 Saranac Avenue, Lake Placid, NY 12946", suits=["shopping","rain"], rainOk=True, cost="$$"),
E("adk-high-peaks-information-center", "ADK High Peaks Information Center (Heart Lake)", "Guides & outfitters", "Adirondak Loj / High Peaks area", "The Adirondack Mountain Club's trailhead hub at Heart Lake: current trail conditions, maps, rentals, a small shop and snacks. Stop here before Mount Jo or any Loj-based hike; parking fills by 7 am on summer weekends.", sub="Trail information / gear", address="1002 Adirondak Loj Road, Lake Placid, NY 12946", website="https://www.adk.org/", suits=["hikers","families"], cost="Parking fee (verify)"),
E("adk-cascade-welcome-center", "ADK Cascade Welcome Center", "Skiing", LP, "The former Cascade Cross-Country Ski Center, now run by the Adirondack Mountain Club: a trail network on Route 73 that links to Mt Van Hoevenberg, ski and snowshoe rentals, lessons and a warming room. Gentler and cheaper than the Olympic centre.", sub="Cross-country / snowshoe", address="4833 Cascade Road, Lake Placid, NY 12946", website="https://www.adk.org/", suits=["winter","families","quiet"], cost="Trail pass (verify)", season="Winter"),
]

# ───────────────────────── ANTIQUES & VINTAGE ─────────────────────────
NEW += [
E("traditions-antiques-lake-placid", "Traditions", "Antiques & vintage", LP, "Antiques and rustic goods with a Great Camp flavour on Saranac Avenue: snowshoes, camp furniture, prints and taxidermy.", sub="Antiques / rustic", address="1975 Saranac Avenue, Lake Placid, NY 12946", suits=["antiques","rain"], rainOk=True, cost="$$–$$$"),
E("twigs-rustic-gallery", "Twigs", "Antiques & vintage", LP, "Multi-vendor rustic gallery with antiques, crafts and locally made Adirondack chairs.", sub="Antiques / crafts", address="Lake Placid, NY 12946", suits=["antiques","shopping"], rainOk=True, cost="$$"),
E("red-canoe-antiques", "Red Canoe Antiques", "Antiques & vintage", SL, "Roadside antiques barn on Route 3 outside Saranac Lake: fishing creels, camp blankets, old postcards, paintings and the occasional gem.", sub="Antiques barn", address="1495 NYS Route 3, Saranac Lake, NY 12983", suits=["antiques","rain"], rainOk=True, cost="$–$$$", season="Seasonal hours (verify)"),
E("lakeview-antiques-keene", "Lakeview Antiques", "Antiques & vintage", KE, "A small shop in an old garage at the end of a driveway in Keene; hit-or-miss and all the better for it.", sub="Antiques", address="Keene, NY 12942", suits=["antiques"], cost="$–$$", season="Verify hours before driving"),
E("champlain-valley-antique-trail", "Champlain Valley antiques run: Keeseville · Willsboro · Essex · Westport", "Antiques & vintage", "Willsboro / Essex", "An hour east the lake towns along Routes 9N and 22 have barns, group shops and Essex's preserved 19th-century main street. Make a day of it with lunch in Essex and the Ausable Chasm on the way back. Shop names change; the county's list is the place to check.", sub="Antiques day trip", website="https://visitadirondacks.com/", suits=["antiques","sightseeing","quiet"], cost="Free to browse", season="Best May–October"),
]

# ───────────────────────── SIGHTSEEING & LEAF-PEEPING ─────────────────────────
NEW += [
E("wilmington-notch-drive", "Wilmington Notch: NY-86 to Lake Placid", "Sightseeing & foliage", "Wilmington Notch (NY-86)", "Your daily commute is one of the great short drives in the Northeast: the West Branch cutting through the Notch under Whiteface's cliffs, with pull-offs at Monument Falls (the postcard Whiteface reflection) and High Falls Gorge. Peak colour usually the first two weeks of October.", sub="Leaf-peeping drive", suits=["sightseeing","families","quiet"], cost="Free", season="Best late September – mid-October", links=[L("NY fall foliage report","https://www.iloveny.com/things-to-do/fall/foliage-report/")], flags=["leaf-peeping"]),
E("monument-falls-pulloff", "Monument Falls pull-off", "Sightseeing & foliage", "Wilmington Notch (NY-86)", "The roadside pull-off on NY-86 where the river widens and Whiteface fills the frame; the most photographed view in the Notch and thirty seconds from the car.", sub="Viewpoint", suits=["sightseeing","families"], cost="Free", flags=["leaf-peeping"]),
E("route-73-cascade-pass-drive", "Route 73 through Cascade Pass to Keene Valley", "Sightseeing & foliage", "Cascade Pass, Route 73", "Cliffs, the two Cascade Lakes, then the long descent into Keene with the High Peaks stacked ahead; Chapel Pond and Giant's cliffs beyond Keene Valley. The other essential foliage drive.", sub="Leaf-peeping drive", suits=["sightseeing","quiet"], cost="Free", season="Best late September – mid-October", flags=["leaf-peeping"]),
E("route-9n-ausable-valley-drive", "Route 9N: Jay to Keene along the East Branch", "Sightseeing & foliage", "Upper Jay", "The quiet way south: farm fields, the East Branch of the Ausable and the Jay Range on your left, then Hurricane's ridge. Fewer cars than Route 73, and it lands you at Baxter Mountain Tavern.", sub="Leaf-peeping drive", suits=["sightseeing","quiet"], cost="Free", flags=["leaf-peeping"]),
E("silver-lake-road-drive", "Silver Lake Road & Union Falls Pond", "Sightseeing & foliage", "Black Brook / Silver Lake", "North from Au Sable Forks through Black Brook past Silver Lake and Taylor Pond to Union Falls: ponds, maples and almost no traffic. Add the short Silver Lake Mountain climb for the view over it all.", sub="Leaf-peeping drive", suits=["sightseeing","quiet","families"], cost="Free", flags=["leaf-peeping"]),
E("adirondak-loj-road-view", "Adirondak Loj Road: the High Peaks panorama", "Sightseeing & foliage", "Adirondak Loj / High Peaks area", "The open fields along Adirondak Loj Road give the classic straight-on view of the MacIntyre Range and Marcy; unbeatable at golden hour and in October. Pull fully off the road.", sub="Viewpoint", suits=["sightseeing","quiet"], cost="Free", flags=["leaf-peeping"]),
E("norman-ridge-view", "Norman Ridge, Vermontville", "Sightseeing & foliage", "Vermontville", "A farm road north of Saranac Lake with a sweeping southern view of Whiteface and the High Peaks across rolling fields; the photographers' secret for sunrise and foliage.", sub="Viewpoint", suits=["sightseeing","quiet"], cost="Free", flags=["leaf-peeping"]),
E("chapel-pond-viewpoint", "Chapel Pond & Giant's Washbowl", "Sightseeing & foliage", KV, "Roadside pond beneath cliffs on Route 73 south of Keene Valley, ringed with colour in autumn and busy with climbers all summer. A five-minute stop or a short, steep hike up to the Washbowl.", sub="Viewpoint / short hike", suits=["sightseeing","hikers"], cost="Free", flags=["leaf-peeping"], links=[AT("giants-washbowl-trail")]),
E("bonnieview-road-wilmington", "Bonnieview Road and the back roads of Wilmington", "Sightseeing & foliage", WI, "Farm lanes off Haselton Road and Bonnieview Road frame Whiteface across open meadows; a bike or slow-drive loop from the house at sunset.", sub="Scenic loop", suits=["sightseeing","quiet","biking"], cost="Free", flags=["leaf-peeping"], drive="From the driveway"),
E("lake-placid-boat-tour", "Lake Placid Marina & Boat Tours", "Sightseeing & foliage", LP, "Narrated hour-long cruises around Lake Placid's islands past the Great Camps, with Whiteface over the water; a restful foliage or rainy-drizzle option that still gets everyone outside.", sub="Scenic boat tour", address="Mirror Lake Drive, Lake Placid, NY 12946", website="https://www.lakeplacidmarina.com/", suits=["families","sightseeing","quiet"], cost="$$ per person (verify)", season="Late May – mid-October", flags=["leaf-peeping"]),
E("poke-o-moonshine-fire-tower", "Poke-O-Moonshine fire tower", "Hiking", "Chesterfield / Keeseville", "A restored fire tower above the Champlain Valley with a view from Whiteface to Vermont's Greens; the Observers' Trail is the gentler route. Superb in foliage season.", sub="Medium", suits=["hikers","sightseeing","families"], cost="Parking fee (verify)", miles=2.4, climbFt=1280, duration="2.5–3.5 hours", tier="Medium", fitness="Steady climb on a good trail.", children="Fine for school-age hikers; tower stairs need supervision.", payoff="Fire-tower panorama over Lake Champlain.", links=[AT("poke-o-moonshine-observers-trail")], flags=["leaf-peeping"]),
E("silver-lake-mountain", "Silver Lake Mountain", "Hiking", "Black Brook / Silver Lake", "Under a mile up to open ledges over Silver Lake, Taylor Pond and Whiteface; one of the best view-for-effort climbs in the region and almost unknown.", sub="Small children", suits=["families","hikers","sightseeing"], cost="Free", miles=1.8, climbFt=900, duration="1.5–2 hours", tier="Small children", fitness="Short but steep in places.", children="Good for confident young walkers; ledges need supervision.", payoff="Ledges over lakes with Whiteface behind.", links=[AT("silver-lake-mountain-trail")], flags=["leaf-peeping"]),
E("bear-den-mountain-wilmington", "Bear Den Mountain", "Hiking", WI, "A moderate climb from the Whiteface ski area's Bear Den lot to a rocky summit with a straight-on look at Whiteface and the Notch. Quiet, local and close.", sub="Medium", suits=["hikers"], cost="Free", miles=4.6, climbFt=1200, duration="3–4 hours", tier="Medium", fitness="Sustained climb; some steep pitches.", children="Best for older children.", payoff="Whiteface and the Wilmington valley from a quiet summit.", links=[AT("bear-den-mountain-trail")]),
E("catamount-mountain", "Catamount Mountain", "Hiking", "Black Brook / Silver Lake", "Short mileage, big character: open rock, a chimney scramble and a bald summit with 360° views over Taylor Pond and Whiteface. Not for small children or wet days.", sub="Difficult", suits=["hikers","adults"], cost="Free", miles=3.6, climbFt=1550, duration="3–4 hours", tier="Difficult", fitness="Steep with rock scrambling and a tight chimney.", children="Older, confident kids only; no dogs unless very agile.", payoff="One of the best small-summit views in the Adirondacks.", links=[AT("catamount-mountain-trail")]),
E("flume-knob", "Flume Knob", "Hiking", WI, "From the Flume trailhead on NY-86, a steady climb to a knob with a fine view of Whiteface and the Notch; the hike locals do after work.", sub="Medium", suits=["hikers"], cost="Free", miles=3.4, climbFt=1000, duration="2.5–3 hours", tier="Medium", fitness="Moderate, steady climbing.", children="School-age and up.", payoff="Whiteface across the valley from a quiet ledge.", links=[AT("flume-knob-trail")]),
E("baxter-mountain", "Baxter Mountain", "Hiking", KE, "The easy classic of the Keene area: a gentle climb to open ledges with the Great Range laid out to the south. Then the tavern at the bottom.", sub="Small children", suits=["families","hikers","sightseeing"], cost="Free", miles=2.4, climbFt=770, duration="1.5–2.5 hours", tier="Small children", fitness="Gentle to moderate.", children="Very good family hike; open ledges to watch.", payoff="Great Range panorama for little effort.", links=[AT("baxter-mountain-trail")], flags=["leaf-peeping"]),
E("roaring-brook-falls", "Roaring Brook Falls", "Hiking", KV, "A ten-minute walk from Route 73 to the base of a 300-foot cascade, or a longer climb to the top of the falls; the easiest big-payoff stop in the valley.", sub="Leisurely / easy", suits=["families","sightseeing"], cost="Free", miles=0.6, climbFt=150, duration="30–60 minutes", tier="Leisurely / easy", fitness="Short walk; the upper route is steeper.", children="Easy to the base; keep children away from the top of the falls.", payoff="A tall waterfall close to the road.", links=[AT("roaring-brook-falls-trail")]),
E("rooster-comb", "Rooster Comb", "Hiking", KV, "From the village of Keene Valley to a rocky summit over the Ausable valley with Giant and the Great Range around you; a proper half-day.", sub="Medium", suits=["hikers"], cost="Free", miles=4.8, climbFt=1750, duration="3.5–4.5 hours", tier="Medium", fitness="Sustained climb with steeper upper sections.", children="Older children with hiking experience.", payoff="A summit right above the village.", links=[AT("rooster-comb-trail")]),
E("pitchoff-balanced-rocks", "Pitchoff Mountain: Balanced Rocks", "Hiking", "Cascade Pass, Route 73", "Across the road from Cascade's trailhead, a steep climb to the Balanced Rocks ledge looking down on the Cascade Lakes and across to Cascade and Porter; far quieter than its famous neighbour.", sub="Medium", suits=["hikers","sightseeing"], cost="Free", miles=3.0, climbFt=1100, duration="2.5–3.5 hours", tier="Medium", fitness="Steep, rooty climbing.", children="Older children.", payoff="Cliff-top view over the Cascade Lakes.", links=[AT("pitchoff-mountain-trail")], flags=["leaf-peeping"]),
E("indian-head-rainbow-falls-amr", "Indian Head & Rainbow Falls (Adirondack Mountain Reserve)", "Hiking", KV, "Perhaps the most photographed view in the Adirondacks: the Lower Ausable Lake from Indian Head's cliff, plus Rainbow Falls on the way. Access is through the private AMR, which requires a free advance parking reservation in season.", sub="Difficult", suits=["hikers","sightseeing"], cost="Free; reservation required", booking="AMR parking reservation (hikeamr.org) May–October", miles=10.5, climbFt=1500, duration="6–8 hours", tier="Difficult", fitness="Long day on a mostly gentle road, then a steep climb.", children="Fit older children only.", payoff="The iconic Lower Ausable Lake view.", links=[L("AMR reservation","https://hikeamr.org/"), AT("indian-head-and-rainbow-falls")], flags=["leaf-peeping"]),
E("haystack-mountain-saranac", "Haystack Mountain (Saranac Lake 6er)", "Hiking", "Ray Brook", "A pleasant climb from Route 86 to open ledges with McKenzie and the High Peaks in view; one of the Saranac Lake 6ers and much quieter than Cascade.", sub="Medium", suits=["hikers"], cost="Free", miles=6.6, climbFt=1240, duration="3.5–4.5 hours", tier="Medium", fitness="Long, mostly gentle approach then a steep finish.", children="Older children.", payoff="Ledges over the Saranac lakes.", links=[AT("haystack-mountain-trail-saranac-lake")]),
E("saranac-lake-6er", "The Saranac Lake 6er challenge", "Hiking", SL, "Climb the six peaks around Saranac Lake (Baker, Haystack, Scarface, McKenzie, Ampersand and St. Regis), ring the bell in Berkeley Green and earn a patch. A great family goal over several visits.", sub="Challenge", website="https://www.saranaclake6er.com/", suits=["hikers","families"], cost="Free; small fee for patch", drive="Trailheads 25–50 min"),
E("lake-placid-9er", "The Lake Placid 9er challenge", "Hiking", LP, "Nine moderate peaks around Lake Placid, from Cobble Hill in the village to Catamount and Big Slide; a season-long project with a patch at the end.", sub="Challenge", website="https://www.lakeplacid9er.com/", suits=["hikers","families"], cost="Free; small fee for patch", drive="Trailheads 10–45 min"),
E("mount-marcy-via-van-hoevenberg", "Mount Marcy via the Van Hoevenberg Trail", "Hiking", "Adirondak Loj / High Peaks area", "New York's highest point, a 14.8-mile round trip from Heart Lake. Start before dawn, carry more than you think, and check the forecast; above the trees it is a different climate. For fit adults with a full day and good weather only.", sub="Difficult", suits=["hikers","adults"], cost="Parking fee (verify)", miles=14.8, climbFt=3200, duration="8–11 hours", tier="Difficult", fitness="A very long, hard day.", children="Not for children.", payoff="The roof of New York.", links=[AT("mount-marcy-via-van-hoevenberg-trail")]),
]

# ───────────────────────── BIKING ─────────────────────────
NEW += [
E("wilmington-bike-park", "Wilmington Bike Park", "Biking", WI, "The town's free skills park behind the visitor centre: pump track, dirt jumps and a progression of features that keeps kids busy for an hour while the adults ride the Flume.", sub="Skills park / pump track", address="Town of Wilmington Recreation Park, NYS Route 86, Wilmington, NY 12997", website="https://www.whitefaceregion.com/recreation/biking/wilmington-bike-park", suits=["families","biking"], cost="Free", season="Spring–fall"),
E("poor-mans-downhill", "Poor Man's Downhill", "Biking", WI, "The classic Wilmington ride: shuttle or pedal up the Whiteface Memorial Highway approach and descend a long, flowy singletrack back to town. Ask Leepoff or BETA about the current shuttle arrangements.", sub="Downhill / shuttle ride", website="https://www.betatrails.org/wilmington.html", suits=["biking","active"], cost="Free (shuttle fee if used)", season="Late spring – fall"),
E("beta-trails-alliance", "Barkeater Trails Alliance (BETA) trail maps", "Biking", WI, "The volunteer group that builds and maintains the mountain-bike and ski trails around Wilmington, Lake Placid and Saranac Lake. Their maps and trail-status posts are the source of truth; buy a map or donate.", sub="Trail organisation / maps", website="https://www.betatrails.org/", suits=["biking","winter"], cost="Donation", drive="Online"),
E("adirondack-rail-trail-full", "Adirondack Rail Trail: Lake Placid to Tupper Lake", "Biking", LP, "The 34-mile converted rail line from Lake Placid through Saranac Lake to Tupper Lake, flat and gravel-surfaced; ride a section out and back or arrange a shuttle. Also groomed for skiing and snowmobiles in winter.", sub="Rail trail", website="https://dec.ny.gov/places/adirondack-rail-trail", suits=["families","biking","quiet"], cost="Free", season="Year-round"),
E("dewey-mountain-bike-trails", "Dewey Mountain trails (summer)", "Biking", SL, "Dewey's ski trails double as a lift-free mountain-bike and hiking network in summer with a mix of grades and a view from the top.", sub="Trail network", address="Dewey Mountain Recreation Center, NYS Route 3, Saranac Lake, NY 12983", website="https://www.deweymountain.com/", suits=["biking","families"], cost="Free (donations)", season="Spring–fall"),
E("mirror-lake-road-loop-ride", "Road cycling: the Ironman loop and River Road", "Biking", LP, "The Ironman bike course from Lake Placid down through the Notch to Wilmington and back via Haselton Road is the region's road-riding classic, with the flat River Road along the West Branch for an easier spin.", sub="Road cycling", suits=["biking","active"], cost="Free", season="Late spring – fall", drive="From the driveway"),
E("whiteface-bike-park-status", "Whiteface Downhill Bike Park (currently closed)", "Biking", WI, "The gondola-served downhill park has been closed in recent seasons. Kept here so guests are not sent to a closed lift; the Flume and Hardy Road networks are the replacement.", sub="Downhill park (closed)", website="https://whiteface.com/", suits=["biking"], cost="—", status="closed"),
]

# ───────────────────────── SKIING & WINTER ─────────────────────────
NEW += [
E("dewey-mountain-recreation-center", "Dewey Mountain Recreation Center", "Skiing", SL, "Saranac Lake's community Nordic centre: groomed and lit lower trails for night skiing, snowshoe loops, rentals and lessons, all for very little money. The relaxed alternative to Mt Van Hoevenberg.", sub="Cross-country / snowshoe", address="NYS Route 3, Saranac Lake, NY 12983", website="https://www.deweymountain.com/", suits=["winter","families","quiet"], cost="$ trail pass (verify)", season="Winter"),
E("mount-pisgah-saranac-lake", "Mount Pisgah Recreation Center", "Skiing", SL, "A small village-owned ski hill with a T-bar, night skiing, a tubing park and a lodge; perfect for first-timers and small children at a fraction of Whiteface's price.", sub="Small ski hill / tubing", address="92 Mount Pisgah Lane, Saranac Lake, NY 12983", website="https://www.mtpisgahadk.com/", suits=["families","winter","value"], cost="$ tickets (verify)", season="Winter"),
E("jackrabbit-ski-trail", "Jackrabbit Ski Trail", "Skiing", LP, "A 35-mile backcountry ski route linking Keene, Lake Placid, Saranac Lake and Paul Smiths through the woods; ski a section from Whiteface Inn Lane or the Cascade area. Ungroomed in places; ask BETA for conditions.", sub="Backcountry ski trail", website="https://www.betatrails.org/jackrabbit-ski-trail.html", suits=["winter","active","quiet"], cost="Free", season="Winter"),
E("otis-mountain", "Otis Mountain", "Skiing", "Elizabethtown", "A tiny volunteer-run community ski hill near Elizabethtown with a rope tow, open weekends when there is snow; charming and free-ish.", sub="Community ski hill", website="https://www.otismountain.com/", suits=["families","winter","quiet"], cost="Donation / small fee (verify)", season="Winter weekends, snow permitting"),
E("titus-mountain", "Titus Mountain Family Ski Center", "Skiing", "Malone", "Family-run mountain north of the Park with easier terrain, night skiing and lower prices; a good change of pace on a busy Whiteface holiday weekend.", sub="Ski area", address="215 Johnson Road, Malone, NY 12953", website="https://www.titusmountain.com/", suits=["families","winter"], cost="$$ tickets (verify)", season="Winter"),
E("whiteface-snowshoe-heaven-hill", "Snowshoe & winter walks: Heaven Hill, Henry's Woods & Peninsula Trails", "Skiing", LP, "Three free, gentle trail networks around Lake Placid that are made for snowshoes and small legs; Henry's Woods off Bear Cub Lane has a lovely lookout loop.", sub="Snowshoe", suits=["families","winter","quiet"], cost="Free", season="Winter", links=[AT("henrys-woods-loop")]),
E("adirondack-rock-and-river", "Adirondack Rock and River Guide Service", "Guides & outfitters", KE, "Keene's climbing and ice-climbing guide service and lodge, with beginner days on real rock and ice. The safe way to try the sport.", sub="Climbing / ice guides", address="Alstead Hill Lane, Keene, NY 12942", website="https://www.rockandriver.com/", suits=["active","adults","teens"], cost="$$$ per day (verify)", booking="Reserve well ahead"),
E("alpine-adventures-keene", "Alpine Adventures", "Guides & outfitters", KE, "Rock and ice climbing, guided hiking and backcountry skiing from Keene since the 1980s.", sub="Climbing / backcountry guides", address="NYS Route 73, Keene, NY 12942", website="https://www.alpineadven.com/", suits=["active","adults"], cost="$$$ (verify)", booking="Reserve ahead"),
E("cloudsplitter-mountain-guides", "Cloudsplitter Mountain Guides", "Guides & outfitters", KV, "Keene Valley-based guides for High Peaks hikes, winter ascents, ice climbing and backcountry skiing; a strong choice for a guided Marcy or Algonquin day.", sub="Hiking / climbing / ski guides", website="https://www.cloudsplitterguides.com/", suits=["active","adults"], cost="$$$ (verify)", booking="Reserve ahead"),
E("middle-earth-expeditions", "Middle Earth Expeditions", "Guides & outfitters", LP, "Long-running Lake Placid outfitter for whitewater rafting on the Hudson, fishing, hiking and ice-climbing trips.", sub="Rafting / fishing / hiking guides", website="https://www.adirondackrafting.com/", suits=["active","families"], cost="$$–$$$ (verify)"),
]

# ───────────────────────── FISHING ─────────────────────────
NEW += [
E("hungry-trout-fly-shop", "Hungry Trout Fly Shop & guide service", "Fishing", WI, "Full-service fly shop on the West Branch with half- and full-day guided trips, casting schools and a youth programme, plus two miles of private water for guests. The obvious first call for a fly-fishing day from the house.", sub="Fly shop / guides", address="5239 NYS Route 86, Wilmington, NY 12997", website="https://hungrytroutflyshop.com/", suits=["fishing","adults","teens"], cost="$$$ guided day (verify)", booking="Book ahead in May–June and September", flags=["preferred-provider"]),
E("ausable-river-two-fly-shop", "Ausable River Two Fly Shop (retired; guide referrals)", "Fishing", WI, "The legendary little shop on Springfield Road has retired from retail but keeps a guide-referral page and sells off remaining stock online. Listed so guests are not sent to a closed door.", sub="Fly shop (retired)", address="1104 Springfield Road, Wilmington, NY 12997", website="https://www.ausablerivertwoflyshop.com/", suits=["fishing"], cost="—", status="closed"),
E("horrocks-outfitting", "Horrocks Outfitting", "Fishing", LP, "Licensed captain and guide with nearly two decades on Lake Placid, the Saranacs and the rivers; fly and light-tackle trips for lake trout, bass and pike.", sub="Lake & river guide", website="https://www.horrocksoutfitting.com/", suits=["fishing","families"], cost="$$$ (verify)", booking="Reserve ahead"),
E("battlefish-charters", "Battlefish Charters", "Fishing", SL, "Guided lake fishing, kayak fishing and winter ice-fishing trips on the Saranac chain.", sub="Lake & ice-fishing charters", website="https://www.battlefishcharter.com/", suits=["fishing","families","winter"], cost="$$$ (verify)", booking="Reserve ahead"),
E("adirondack-troutfitters", "Adirondack TrOutfitters", "Fishing", SL, "Half- and full-day guided trips for trout, bass and pike on Upper Saranac, Lake Placid and nearby waters.", sub="Fishing guide", website="https://www.adirondacktroutfitters.com/", suits=["fishing"], cost="$$$ (verify)", booking="Reserve ahead"),
E("jones-outfitters-lake-placid", "Jones Outfitters", "Fishing", LP, "Main Street's fly shop since the 1950s, with guided trips, lessons and canoe and kayak rentals on Mirror Lake. Confirm current hours; the shop has changed hands over the years.", sub="Fly shop / guides / paddle rentals", address="2733 Main Street, Lake Placid, NY 12946", website="https://www.jonesoutfitters.com/", suits=["fishing","water"], cost="$$–$$$ (verify)"),
E("ausable-river-association", "Ausable River Association (AsRA)", "Fishing", WI, "The river's stewardship group: flow and temperature data, river-access maps, clean-boots guidance and events. Their site tells you when the West Branch is too warm to fish responsibly.", sub="River information", address="1181 Haselton Road, Wilmington, NY 12997", website="https://www.ausableriver.org/", suits=["fishing","quiet"], cost="Free"),
E("nys-fishing-license", "New York fishing licence & regulations", "Fishing", "—", "Everyone 16 and over needs a licence (one-day, seven-day and annual options for non-residents, bought online in minutes). The West Branch has special catch-and-release stretches; check the DEC regulations before wading in.", sub="Licence / rules", website="https://dec.ny.gov/regulatory/permits-licenses/sporting-and-use/sporting/fishing-licenses", suits=["fishing"], cost="Licence fee", drive="Online"),
E("ice-fishing-lake-placid-saranac", "Ice fishing on Lake Placid & the Saranacs", "Fishing", LP, "From January the lakes freeze hard enough for tip-ups and shanties; go with a guide the first time, and never trust ice you have not checked.", sub="Ice fishing", suits=["fishing","winter"], cost="Guide fee (verify)", season="January – March, ice permitting", know="Check ice reports; a guide is the safe first outing."),
]

# ───────────────────────── WATER & BOATING ─────────────────────────
NEW += [
E("mirror-lake-boat-rentals", "Mirror Lake Boat Rentals", "Water & boating", LP, "Family-run rental on the shore of Mirror Lake: kayaks, canoes, paddleboards, pedal boats and electric boats by the hour, no reservation needed, dogs welcome. The simplest water hour in town.", sub="Paddle & electric boat rental", address="Mirror Lake Drive, Lake Placid, NY 12946", website="https://www.mirrorlakeboatrentals.com/", suits=["families","water","dogs"], cost="$$ hourly (verify)", season="Ice-out to mid-October"),
E("placid-boat-rentals", "Placid Boat Rentals", "Water & boating", LP, "Pontoons, fishing boats and paddle craft on Lake Placid itself, for a day among the islands and Great Camps.", sub="Motor & pontoon rental", website="https://placidboatrentals.com/", suits=["families","groups","water"], cost="$$$ per day (verify)", season="Late May – early October", booking="Reserve in July–August"),
E("downstairs-boat-rental", "Downstairs Boat Rental", "Water & boating", LP, "Main Street kayak, canoe, paddleboard, hydrobike and pedal-boat rental on Mirror Lake, plus a Duffy electric launch for a lazy cruise.", sub="Paddle rental", address="Main Street, Lake Placid, NY 12946", website="https://downstairsboatrental.com/", suits=["families","water"], cost="$ hourly (verify)", season="Summer–early fall"),
E("lake-placid-public-beach", "Lake Placid Public Beach (Mirror Lake)", "Water & boating", LP, "The village beach on Mirror Lake with lifeguards, a roped swimming area and a lawn; free, central and the classic hot-afternoon fix.", sub="Beach", address="Parkside Drive, Lake Placid, NY 12946", suits=["families","water"], cost="Free", season="Late June – Labor Day (verify lifeguard hours)"),
E("second-pond-lower-saranac-paddle", "Paddling the Lower Saranac from Second Pond", "Water & boating", SL, "Put in at the state launch on Route 3 and paddle into Lower Saranac's islands and campsites; a half-day loop with picnic rocks and loons, best with an outfitter's canoe and map.", sub="Flatwater paddling", suits=["water","quiet","active"], cost="Free launch; rental extra", season="May – October"),
E("chapel-pond-paddle", "Chapel Pond paddle", "Water & boating", KV, "A small roadside pond under cliffs where a kayak feels like an alpine lake; twenty minutes of paddling with climbers overhead.", sub="Flatwater paddling", suits=["water","quiet"], cost="Free", season="May – October"),
E("taylor-pond-campground", "Taylor Pond & Silver Lake: swimming and boat launch", "Water & boating", "Black Brook / Silver Lake", "DEC campground with a beach, boat launch and quiet water under Catamount; combine with the Silver Lake Mountain hike for a full, uncrowded day.", sub="Lake / campground", website="https://dec.ny.gov/places/taylor-pond-campground", suits=["families","water","quiet"], cost="Day-use fee (verify)", season="Late May – early September"),
E("ausable-chasm-rafting", "Ausable Chasm: raft & tube float", "Water & boating", "Keeseville", "The Chasm's own raft and inner-tube float through the lower gorge is the gentlest whitewater in the region and the best part of a visit for most kids; included with certain passes.", sub="Gentle rafting / tubing", website="https://www.ausablechasm.com/", suits=["families","water"], cost="Included in pass options (verify)", season="Late spring – fall, water levels permitting"),
]

# ───────────────────────── RAINY DAY / INDOOR ─────────────────────────
NEW += [
E("mt-van-hoevenberg-climbing-wall", "Indoor climbing wall at Mt Van Hoevenberg", "Rainy day", "Lake Placid / Olympic Sports Complex", "A 30-foot top-rope wall and bouldering cave inside the Mountain Pass Lodge with rentals and staff who teach beginners; a couple of hours of wet-weather adventure for anyone over about five.", sub="Indoor climbing", address="220 Bobsled Run Lane, Lake Placid, NY 12946", website="https://mtvanhoevenberg.com/", suits=["families","rain","active"], rainOk=True, cost="$$ (verify)"),
E("olympic-center-public-skating", "Public skating at the Olympic Center", "Rainy day", LP, "Skate on a real Olympic rink inside the Olympic Center on scheduled public sessions, with rentals; a rainy or bitter-cold-day certainty.", sub="Indoor skating", address="2634 Main Street, Lake Placid, NY 12946", website="https://lakeplacidlegacysites.com/", suits=["families","rain","winter"], rainOk=True, cost="$ + rentals (verify)", booking="Check the day's public-session times"),
E("saranac-lake-civic-center", "Saranac Lake Civic Center", "Rainy day", SL, "Community ice rink with public skating sessions and rentals; cheaper and quieter than Lake Placid.", sub="Indoor skating", address="Ampersand Avenue, Saranac Lake, NY 12983", suits=["families","rain","winter"], rainOk=True, cost="$ (verify)", season="Fall – spring"),
E("bluseed-studios", "BluSeed Studios", "Arts & culture", SL, "Artists' studios with a 2,000-square-foot gallery and performance space: exhibitions, concerts and printmaking and ceramics workshops open to visitors. Check what is on.", sub="Gallery / workshops / concerts", address="24 Cedar Street, Saranac Lake, NY 12983", website="https://www.bluseedstudios.org/", suits=["culture","rain"], rainOk=True, cost="Free gallery; tickets and class fees vary"),
E("adirondack-sky-center", "Adirondack Sky Center & Observatory", "Arts & culture", "Tupper Lake", "Public stargazing nights under some of the darkest skies in the East, with a roll-off-roof observatory and volunteer astronomers. Pair with a Wild Center day and stay for dark.", sub="Observatory / stargazing", address="178 Big Wolf Road, Tupper Lake, NY 12986", website="https://www.adirondackskycenter.org/", suits=["families","culture","quiet"], cost="Donation (verify)", season="Public nights on a schedule; clear skies only"),
E("adirondack-experience-museum", "Adirondack Experience, the Museum on Blue Mountain Lake", "Arts & culture", "Blue Mountain Lake", "The Park's great museum: 121 acres of exhibits on boats, logging, Great Camps and Adirondack life, with a lakeside café and plenty for children. A long drive that fills a whole day; leave early.", sub="Regional museum", address="9097 NYS Route 30, Blue Mountain Lake, NY 12812", website="https://www.theadkx.org/", suits=["families","culture","rain"], rainOk=True, cost="$$ admission (verify)", season="Late May – mid-October"),
E("natural-stone-bridge-and-caves", "Natural Stone Bridge & Caves", "Family fun", "Pottersville", "Self-guided trails over the largest marble cave entrance in the East, with caves, potholes and a gem-panning station; snowshoeing in winter. Worth combining with a Schroon Lake lunch.", sub="Caves / geology park", address="535 Stone Bridge Road, Pottersville, NY 12860", website="https://www.stonebridgeandcaves.com/", suits=["families","sightseeing"], cost="$$ admission (verify)", season="Late May – mid-October; winter snowshoe weekends"),
E("keene-arts", "Keene Arts", "Arts & culture", KE, "Gallery and performance space in a converted church in Keene with summer exhibitions, concerts and talks.", sub="Gallery / performances", address="NYS Route 73, Keene, NY 12942", website="https://www.keenearts.com/", suits=["culture","rain"], rainOk=True, cost="Free gallery; tickets vary", season="Mostly summer–fall"),
E("uihlein-maple-forest", "Uihlein Maple Research Forest (Cornell)", "Farms & local life", LP, "Cornell's maple research station on Bear Cub Lane sells its own syrup and opens for demonstrations in sugaring season (March); a sweet, short stop.", sub="Maple / sugaring", address="157 Bear Cub Lane, Lake Placid, NY 12946", website="https://blogs.cornell.edu/uihleinmaple/", suits=["families","food"], cost="Free; syrup for sale", season="Sugaring March–April; shop hours vary (verify)"),
]

# ───────────────────────── ESSENTIALS ─────────────────────────
NEW += [
E("terry-robards-wines", "Terry Robards Wines & Spirits", "Essentials", LP, "The well-stocked wine and liquor shop on Saranac Avenue; New York state law keeps wine and spirits out of supermarkets, so this is the stop.", sub="Wine & spirits", address="Saranac Avenue, Lake Placid, NY 12946", suits=["essentials"], cost="$$"),
E("wilmington-visitor-center", "Whiteface Region Visitor Center (Wilmington)", "Essentials", WI, "The town's visitor bureau on NY-86 by the bike park: maps, event listings, restrooms and staff who know the trails. Its website is the Whiteface Region calendar.", sub="Visitor information", address="5753 NYS Route 86, Wilmington, NY 12997", website="https://www.whitefaceregion.com/", suits=["essentials","families"], cost="Free"),
E("dec-trail-conditions", "DEC Adirondack backcountry information & trail conditions", "Essentials", "—", "The state's weekly backcountry report: trail closures, bridge washouts, mud-season advisories, fire danger and High Peaks rules (bear canisters, group sizes). Read it the night before any hike.", sub="Trail conditions", website="https://dec.ny.gov/places/adirondack-backcountry-information", suits=["hikers","essentials"], cost="Free", drive="Online"),
E("whiteface-webcams-weather", "Whiteface Mountain webcams & summit weather", "Essentials", WI, "Live cameras from the summit and base plus the mountain forecast; the quickest way to decide between the Memorial Highway and a rainy-day plan.", sub="Webcams / weather", website="https://whiteface.com/mountain/webcams/", suits=["essentials","sightseeing"], cost="Free", drive="Online"),
E("amr-hiker-parking-reservations", "AMR hiker parking reservations (Route 73 trailheads)", "Essentials", KV, "Free but mandatory advance reservations for the Adirondack Mountain Reserve lot in St. Huberts from May through October; without one you cannot park for Indian Head, Noonmark or the Ausable Lakes.", sub="Trailhead reservations", website="https://hikeamr.org/", suits=["hikers","essentials"], cost="Free", season="May – October", drive="Online"),
]

# ───────────────────────── apply ─────────────────────────
by_id = {p["id"]: p for p in d["places"]}
added = updated = 0
for p in NEW:
    if p["id"] in by_id: by_id[p["id"]].update(p); updated += 1
    else: d["places"].append(p); by_id[p["id"]] = p; added += 1

for p in d["places"]:
    p.setdefault("commentary", "")

# owner go-to placeholders: leave a clearer hint about the likeliest match
for p in d["places"]:
    if p["id"].startswith("46er"):
        p["knowBefore"] = "OWNER TO CONFIRM: no venue named '46er' was found in Lake Placid or Wilmington. The 46'er Pale Ale is Lake Placid Pub & Brewery's flagship beer, so this may mean the Pub & Brewery. Confirm which restaurant is meant."
    if p["id"].startswith("rooftop-bar"):
        p["knowBefore"] = "Likely Cloudsplitter Rooftop Bar at the Grand Adirondack Hotel (2520 Main St), now in the library as its own entry; confirm and this placeholder will be removed."
        p["status"] = "placeholder"

# categories & clusters
for c in ["Bars & nightlife", "Breweries, cider & spirits", "Olympic sites", "Events & festivals", "Shops & outfitters", "Antiques & vintage"]:
    if c not in d["meta"]["categories"]: d["meta"]["categories"].append(c)
d["meta"]["sources"]["[G2]"] = "Library seed 2026-09-08 — real places drawn from regional tourism sites (lakeplacid.com, whitefaceregion.com, saranaclake.com, visitadirondacks.com), official sites and general knowledge; every detail unverified until its first vetting cycle"
d["meta"]["commentary"] = {"field": "commentary", "purpose": "Owner colour commentary shown to guests as 'From Adam' on cards and in the stay guide", "worksheet": "reviews/commentary-worksheet.md", "apply": "python3 vet.py commentary reviews/commentary-worksheet.md"}
CL = {c["key"]: c for c in d["meta"]["clusters"]}
def add_towns(key, towns):
    for t in towns:
        if t not in CL[key]["towns"]: CL[key]["towns"].append(t)
add_towns("jay", ["Black Brook / Silver Lake"])
add_towns("saranac", ["Bloomingdale", "Vermontville"])
add_towns("far", ["Chesterfield / Keeseville", "Blue Mountain Lake", "Pottersville", "Malone", "Willsboro / Essex", "Lake Placid / Ray Brook / Saranac Lake"])
d["meta"]["updated"] = TODAY
json.dump(d, open(P, "w"), indent=1, ensure_ascii=False)
print(f"added {added}, updated {updated}, total {len(d['places'])}")
