# -*- coding: utf-8 -*-
"""
Curated account & competitive intelligence transcribed from the
Monteris NeuroBlate Northeast Territory Plan (2026 Operating Plan, Jul 2026).
This is the qualitative overlay that field-confirms platform, users, referrers,
and the addressable reservoirs used to validate the potential-volume model.
"""

# Reservoirs are given in the deck as "~<addressable> addressable of <pool>".
# The implied addressable fraction is a uniform ~5% of the raw claims pool.
ADDRESSABLE_FRACTION = 0.05  # blended, LITT-appropriate + realistically convertible / yr

TERRITORY = {
    "cases_ours_3yr": 197,
    "cases_competitor_3yr": 357,
    "net_sales_3yr": 4.33e6,
    "category_penetration": 0.105,
    "candidate_universe_yr": 1490,
    "accounts_in_plan": 18,
    "mapped_physicians": 58,
    "avg_rev_per_case": 18300,
    "quota_2026": 106,
    "cases_ytd_2026": 44,
}

# platform vocabulary
NEUROBLATE = "NeuroBlate (Monteris — ours)"
VISUALASE = "Visualase (Medtronic — competitor)"
CLEARPOINT = "ClearPoint (competitor)"
UNVERIFIED = "Unverified — confirm in field"

ACCOUNTS = [
    {
        "rank": 1, "name": "Columbia (NYP)", "acronym": "CUMC", "system": "NewYork-Presbyterian",
        "class": "Installed", "posture": "Expand, priority", "platform": [NEUROBLATE, VISUALASE],
        "cases_logged": 14, "trend": "Up",
        "net_sales_by_year": {"2024": 16000, "2025": 120000, "2026_ytd": 343000, "2026_proj": 633000},
        "situation": "Fastest-growing account by revenue. McKhann runs mostly primary-tumor LITT (12 primary, 2 mets) over an enormous epilepsy, neuro-onc and referral base. McKhann is leaving for Emory; Gill is the successor. Brett Youngerman shows 2 LITT in claims not in our log (Visualase?), with an in-house Visualase rep on site.",
        "surgeons": [("Guy McKhann", 9), ("Brian Gill", 5)],
        "referrers": [("Guy McKhann", "Primary", 3), ("Maria Ordonez", "Metastasis", 2),
                      ("Peter CheiWay Pan", "Primary", 2), ("Aya Haggiagi", "Primary", 1)],
        "reservoirs": {"Mets": (22, 434), "Radiation necrosis": (4, 76),
                       "Intractable epilepsy": (24, 487), "Recurrent GBM": (0, 4)},
        "user_targets": ["Brian Gill", "Raymond F Sekula", "Neil Feldstein", "Jeffrey N Bruce"],
        "epilepsy_referrers": [("Samuel E Koszer", 344), ("Shraddha Srinivasan", 96)],
        "necrosis_referrers": [("Michael Waldrop", 217), ("Katherine D Brodie", 206), ("Wen R Zhang", 189)],
        "business_potential_yr": 108352, "incremental_cases": 8, "win": "High",
    },
    {
        "rank": 2, "name": "Yale New Haven", "acronym": "YALE", "system": "Yale New Haven Health System",
        "class": "Installed", "posture": "Defend + expand", "platform": [NEUROBLATE],
        "cases_logged": 55, "trend": "Flat",
        "net_sales_by_year": {"2024": 350000, "2025": 609000, "2026_ytd": 1130000, "2026_proj": 1270000},
        "situation": "Territory flagship and strongest relationship. Chiang is a disclosed Monteris consultant and the dominant necrosis author (48 mets/RN, only 2 primary, no recurrent). Epilepsy LITT program is weak through Damisah, who has high affinity for open crani. Volume limited by internal politics.",
        "surgeons": [("Veronica Chiang", 50), ("Eyiyemisi Damisah", 5)],
        "referrers": [("Sarah Goldberg", "Metastasis", 5), ("Harriet Kluger", "Metastasis", 4),
                      ("Dennis Spencer", "Metastasis/Primary", 3), ("Michael Cohenuram", "Metastasis", 3)],
        "reservoirs": {"Mets": (111, 2211), "Radiation necrosis": (1, 20),
                       "Intractable epilepsy": (38, 755), "Recurrent GBM": (0, 2)},
        "user_targets": ["Eyiyemisi Damisah", "Jennifer A Moliterno Gunel", "Sacit B Omay", "Jacky T Yeung"],
        "epilepsy_referrers": [("Aline Herlopian", 234), ("Nicholas A Blondin", 184), ("Lawrence J Hirsch", 163)],
        "necrosis_referrers": [("Veronica L Chiang", 49), ("Jennifer A Moliterno Gunel", 211), ("Michael J Grant", 60)],
        "business_potential_yr": 141291, "incremental_cases": 9, "win": "Medium",
    },
    {
        "rank": 3, "name": "Brigham & Women's", "acronym": "BWH", "system": "Mass General Brigham",
        "class": "Installed", "posture": "Defend, capital threat", "platform": [NEUROBLATE, CLEARPOINT],
        "cases_logged": 23, "trend": "Down",
        "net_sales_by_year": {"2024": 361000, "2025": 218000, "2026_ytd": 15000, "2026_proj": 234000},
        "situation": "Revenue fell from $361K to $15K under a ClearPoint capital threat from the Mass General Brigham merger — Mark Richardson (MGH) is a paid ClearPoint consultant pushing system standardization. Golby is the senior tumor champion who actively defended us. Rolston knows our system but wants to align with Richardson.",
        "surgeons": [("John Rolston", 17), ("Alexandra Golby", 6)],
        "referrers": [("Steven Daniel Tobochnik", "Epilepsy", 4), ("Barbara Dworetzky", "Epilepsy", 3),
                      ("David Reardon", "Epilepsy/Metastasis", 2), ("Jong Woo Lee", "Epilepsy", 2)],
        "reservoirs": {"Mets": (308, 6166), "Radiation necrosis": (1, 18),
                       "Intractable epilepsy": (307, 6140), "Recurrent GBM": (1, 20)},
        "user_targets": ["Omar Arnaout", "Timothy R Smith", "William T Curry", "Shivani D Rangwala"],
        "epilepsy_referrers": [("Masanori Takeoka", 1163), ("Jurriaan M Peters", 565), ("Jeffrey Bolton", 459)],
        "necrosis_referrers": [("Luke Peng", 81), ("Itai M Pashtan", 58), ("Monica Krishnan", 55)],
        "business_potential_yr": 206176, "incremental_cases": 8, "win": "Medium",
    },
    {
        "rank": 4, "name": "Beth Israel Deaconess", "acronym": "BID", "system": "Beth Israel Lahey Health",
        "class": "Contested", "posture": "Re-engage + open", "platform": [NEUROBLATE, VISUALASE],
        "cases_logged": 4, "trend": "Down",
        "net_sales_by_year": {"2024": 15000, "2025": 21000, "2026_ytd": 39000, "2026_proj": 104000},
        "situation": "Stalled tumor-only account. Vega (primary user) disengaged over MRI friction; claims show 16 LITT against the 4 logged. Josh Aronson may be using Visualase. Outside-indication research teed up (cavernous malformations with Ogilvy's endovascular team).",
        "surgeons": [("Rafael A Vega", 4)],
        "referrers": [("Lauren Hertan", "Metastasis/Primary", 2)],
        "reservoirs": {"Mets": (68, 1360), "Radiation necrosis": (1, 10),
                       "Intractable epilepsy": (27, 545), "Recurrent GBM": (0, 7)},
        "user_targets": ["Christopher S Ogilvy", "Ron L Alterman", "Philipp Taussky"],
        "epilepsy_referrers": [("Trudy Pang", 231), ("Niravkumar Barot", 106), ("Volney Sheen", 87)],
        "necrosis_referrers": [("Gabriel P Simon", 74), ("Rafael A Vega", 36), ("Ron L Alterman", 7)],
        "business_potential_yr": 64480, "incremental_cases": 4, "win": "Medium",
    },
    {
        "rank": 5, "name": "Nemours Children's (DE)", "acronym": "NEM", "system": "Nemours Children's Health",
        "class": "Installing", "posture": "Onboard, new (closed)", "platform": [NEUROBLATE],
        "cases_logged": 0, "trend": "New",
        "net_sales_by_year": {},
        "situation": "New NeuroBlate account, just closed, extending south into Delaware pediatrics. Catherine Wassef (Colorado-trained pediatric neurosurgeon, epilepsy + MIS focus) is the champion. Lily Tran leaving for Yale.",
        "surgeons": [("Catherine Wassef", 0)],
        "referrers": [],
        "reservoirs": {},
        "user_targets": ["Joseph Piatt", "Catherine Wassef"],
        "epilepsy_referrers": [("Lily H Tran", 322), ("Andrew I Mower", 146), ("Stephen J Falchek", 127)],
        "necrosis_referrers": [("Joseph H Piatt", 115), ("Rosalie T Recto", 101), ("Joanna Costa", 91)],
        "business_potential_yr": 91635, "incremental_cases": 5, "win": "High",
    },
    {
        "rank": 6, "name": "University of Vermont", "acronym": "UVM", "system": "University of Vermont Health",
        "class": "Pipeline", "posture": "Close, in progress", "platform": [NEUROBLATE],
        "cases_logged": 0, "trend": "New",
        "net_sales_by_year": {},
        "situation": "Active opportunity, northern New England anchor. Penar is senior neurosurgeon, Liebelt newer faculty; no LITT there yet. Landing capital and confirming a committed first user.",
        "surgeons": [("Paul Penar", 0), ("Brandon Liebelt", 0)],
        "referrers": [],
        "reservoirs": {},
        "user_targets": ["Paul L Penar", "Brandon D Liebelt", "Katrina A Ducis"],
        "epilepsy_referrers": [("Souzana Obretenova", 35), ("James T Boyd", 4), ("Oluwatosin Akintola", 1)],
        "necrosis_referrers": [("Brandon D Liebelt", 62), ("Daniel Caloras", 28), ("Alissa A Thomas", 21)],
        "business_potential_yr": 73308, "incremental_cases": 4, "win": "High",
    },
    {
        "rank": 7, "name": "Mount Sinai", "acronym": "MSSM", "system": "Mount Sinai Health System",
        "class": "Competitive", "posture": "Verify — then convert", "platform": [CLEARPOINT],
        "cases_logged": 0, "trend": "Competitive",
        "net_sales_by_year": {},
        "situation": "Two real laser surgeons: Fedor Panov (8 LITT, 104 intractable-epilepsy patients) and Saadi Ghatan (4, chair-level). Largest untapped epilepsy pool in the plan, opened through Panov and LAANTERN. Monteris revenue on the books with zero logged cases — verify what is running.",
        "surgeons": [("Fedor Panov", 8), ("Saadi Ghatan", 4)],
        "referrers": [],
        "reservoirs": {},
        "user_targets": ["Fedor Panov", "Saadi Ghatan", "Raj K Shrivastava", "Theodore H Schwartz"],
        "epilepsy_referrers": [("Gena R Ghearing", 441), ("Maite D Talbott", 312), ("Kyusang S Lee", 188)],
        "necrosis_referrers": [("John W Liang", 84), ("Joshua B Bederson", 58), ("Raj K Shrivastava", 49)],
        "business_potential_yr": 91635, "incremental_cases": 5, "win": "Medium",
    },
    {
        "rank": 8, "name": "Westchester Medical Center", "acronym": "WMC", "system": "WMC Health",
        "class": "Installed", "posture": "Defend + grow", "platform": [NEUROBLATE],
        "cases_logged": 29, "trend": "Up",
        "net_sales_by_year": {"2024": 269000, "2025": 133000, "2026_ytd": 245000, "2026_proj": 329000},
        "situation": "Growing across Muh, Hanft and Sukul. Hanft came out of the Danish Visualase school and now runs NeuroBlate — a live conversion reference for nearby Visualase-trained surgeons. Steven Wolf drives epilepsy referrals.",
        "surgeons": [("Carrie Rebecca Muh", 11), ("Simon Hanft", 11), ("Vishad Sukul", 6), ("Jared Pisapia", 1)],
        "referrers": [("Steven Wolf", "Epilepsy", 8), ("Tracey Milligan", "Epilepsy", 3),
                      ("Tatyana Gitlevich", "Epilepsy/Primary", 2), ("Michael Tobias", "Epilepsy", 1)],
        "reservoirs": {"Mets": (5, 96), "Radiation necrosis": (0, 9),
                       "Intractable epilepsy": (61, 1212), "Recurrent GBM": (0, 1)},
        "user_targets": ["Rachana Tyagi", "Avinash L Mohan", "Michael E Tobias"],
        "epilepsy_referrers": [("Steven Wolf", 716)],
        "necrosis_referrers": [("Simon Hanft", 12), ("Charles Fleischner", 10), ("Carrie R Muh", 7)],
        "business_potential_yr": 84160, "incremental_cases": 5, "win": "High",
    },
    {
        "rank": 9, "name": "Boston Children's", "acronym": "BCH", "system": "Mass General Brigham",
        "class": "Competitive", "posture": "Verify, then pursue", "platform": [UNVERIFIED],
        "cases_logged": 0, "trend": "Competitive",
        "net_sales_by_year": {},
        "situation": "Highest LITT volume anywhere in the territory (85 cases / 3 yr, ~28/yr, ~$518K none of it ours). Scellig Stone runs the program (66 cases). Platform unknown — effort here is blind until confirmed. NeuroBlate reportedly once installed; switched over Monteris personnel changes, not technology.",
        "surgeons": [("Scellig S Stone", 66), ("Joshua P Aronson", 12), ("Shiva L Kashanipour", 7)],
        "referrers": [],
        "reservoirs": {},
        "user_targets": ["Scellig S Stone", "Omar Arnaout", "Timothy R Smith", "William T Curry"],
        "epilepsy_referrers": [("Masanori Takeoka", 1163), ("Steven Wolf", 716), ("Jurriaan M Peters", 565)],
        "necrosis_referrers": [("Itai M Pashtan", 58), ("Omar Arnaout", 66), ("Wenya L Bi", 63)],
        "business_potential_yr": 0, "incremental_cases": 0, "win": "Long-horizon",
    },
    {
        "rank": 10, "name": "NYU Langone", "acronym": "NYU", "system": "NYU Langone Health",
        "class": "Installed", "posture": "Grow", "platform": [NEUROBLATE],
        "cases_logged": 21, "trend": "Up",
        "net_sales_by_year": {"2024": 270000, "2025": 60000, "2026_ytd": 111000, "2026_proj": 182000},
        "situation": "Growing across a four-surgeon base (Rozman, Dastagirzada, Placantonakis, Hidalgo). Diffuse momentum that must concentrate in one or two drivers.",
        "surgeons": [("Peter Rozman", 8), ("Yosef Dastagirzada", 7), ("Dimitris Placantonakis", 5), ("Teresa Hidalgo", 1)],
        "referrers": [("Cigdem Akman", "Epilepsy", 5), ("Amy Jongeling", "Epilepsy", 2),
                      ("Andrew Christiana", "Epilepsy", 2), ("Marissa Barbaro", "Primary", 2)],
        "reservoirs": {"Mets": (125, 2503), "Radiation necrosis": (26, 519),
                       "Intractable epilepsy": (64, 1271), "Recurrent GBM": (1, 22)},
        "user_targets": ["John G Golfinos", "Donato Pacione", "Dennis London"],
        "epilepsy_referrers": [("Daniel J Luciano", 396), ("Christopher J Elder", 221), ("Daniel Friedman", 205)],
        "necrosis_referrers": [("Amy Palermo", 91), ("Salman Azhar", 90), ("Marissa A Barbaro", 80)],
        "business_potential_yr": 70260, "incremental_cases": 4, "win": "High",
    },
    {
        "rank": 11, "name": "Stony Brook", "acronym": "SUH", "system": "Stony Brook Medicine",
        "class": "Installed", "posture": "Grow + de-risk", "platform": [NEUROBLATE],
        "cases_logged": 14, "trend": "Up",
        "net_sales_by_year": {"2024": 170000, "2025": 82000, "2026_ytd": 151000, "2026_proj": 239000},
        "situation": "Mikell drives essentially all volume (epilepsy + some tumor). Single-surgeon concentration is the risk — one departure from zero. Needs a second adopter.",
        "surgeons": [("Charles Mikell", 14)],
        "referrers": [("Shennan Weiss", "Epilepsy", 3), ("Agnieszka Kowalska", "Primary", 1),
                      ("Errol Orehek", "Primary", 1)],
        "reservoirs": {"Mets": (3, 68), "Radiation necrosis": (0, 1), "Intractable epilepsy": (5, 100)},
        "user_targets": ["David Chesler", "Alexander Winkler-Schwartz"],
        "epilepsy_referrers": [("Olga Selioutski", 81), ("Guy Schwartz", 1)],
        "necrosis_referrers": [("David A Chesler", 36), ("Charles B Mikell", 27), ("Cathy Coleman", 1)],
        "business_potential_yr": 88396, "incremental_cases": 4, "win": "Medium",
    },
    {
        "rank": 12, "name": "Hackensack Meridian — JFK (Edison, NJ)", "acronym": "HJFK", "system": "Hackensack Meridian Health",
        "class": "Installed", "posture": "System play", "platform": [NEUROBLATE],
        "cases_logged": 4, "trend": "Down",
        "net_sales_by_year": {"2024": 27000, "2025": 20000, "2026_ytd": 37000, "2026_proj": 37000},
        "situation": "Two of our users here (Milano, Shekhtman) at JFK in Edison NJ. Hackensack Meridian is a large multi-hospital system — JFK is one entry point into a much bigger footprint (Jersey Shore, Hackensack UMC). Hackensack UMC is a SEPARATE competitive target (Danish, Visualase, 33 LITT).",
        "surgeons": [("Vanessa Milano", 3), ("Eugenia Shekhtman", 1)],
        "referrers": [("Joseph Landolfi", "Primary", 1), ("Palak Patel", "Epilepsy", 1)],
        "reservoirs": {},
        "user_targets": [],
        "epilepsy_referrers": [],
        "necrosis_referrers": [],
        "business_potential_yr": 0, "incremental_cases": 0, "win": "Long-horizon",
    },
    {
        "rank": 13, "name": "Memorial Sloan Kettering", "acronym": "MSK", "system": "Memorial Sloan Kettering Cancer Center",
        "class": "Installed", "posture": "Protect + develop referral", "platform": [NEUROBLATE],
        "cases_logged": 13, "trend": "Down",
        "net_sales_by_year": {"2024": 111000, "2025": 22000, "2026_ytd": 40000, "2026_proj": 116000},
        "situation": "Near-zero open neurosurgery, so this is a referral play, not surgeon conversion. Decline is upstream in neuro-onc and rad-onc. Souweidane (top pediatric neurosurgeon) WANTS TO START A PROGRAM AT CORNELL.",
        "surgeons": [("Mark Souweidane", 7), ("Nelson Moss", 4), ("Cameron Brennan", 2)],
        "referrers": [("Cameron Brennan", "Primary", 1), ("Craig Nolan", "Primary", 1),
                      ("John Cuaron", "Primary", 1), ("Mark Mittler", "Primary", 1)],
        "reservoirs": {"Mets": (422, 8431), "Radiation necrosis": (3, 64)},
        "user_targets": ["Rabih Bou Nassif", "Viviane S Tabar", "Cameron W Brennan", "Kenny Kwok Hei Yu"],
        "epilepsy_referrers": [],
        "necrosis_referrers": [("Matthias A Karajannis", 7), ("Catherine E Scorrano", 4), ("Fiorella Iglesias Cardenas", 1)],
        "business_potential_yr": 75404, "incremental_cases": 4, "win": "Medium",
    },
    {
        "rank": 14, "name": "Jersey Shore (Hackensack Meridian)", "acronym": "JSUMC", "system": "Hackensack Meridian Health",
        "class": "Competitive", "posture": "Convert — active", "platform": [VISUALASE],
        "cases_logged": 0, "trend": "Competitive",
        "net_sales_by_year": {},
        "situation": "Shabbar Danish is the highest-volume laser surgeon in the Hackensack Meridian network (9 LITT here + 31 at Hackensack UMC). A Monteris system is already in value analysis at Jersey Shore awaiting a trial — an active deal, not a cold account.",
        "surgeons": [("Shabbar F Danish", 9), ("Nitesh V Patel", 2), ("Aasim S Kazmi", 1)],
        "referrers": [],
        "reservoirs": {},
        "user_targets": ["Lawrence Daniels", "Aasim S Kazmi"],
        "epilepsy_referrers": [("Henry Park", 6), ("Carlos Eduardo Silva Correia", 1)],
        "necrosis_referrers": [("Carlos Eduardo Silva Correia", 144), ("Krista K Schneider", 100), ("Henry Park", 93)],
        "business_potential_yr": 0, "incremental_cases": 0, "win": "Long-horizon",
    },
    {
        "rank": 15, "name": "Temple University Hospital", "acronym": "TUH", "system": "Temple Health",
        "class": "Installed", "posture": "Grow", "platform": [NEUROBLATE],
        "cases_logged": 10, "trend": "Up",
        "net_sales_by_year": {"2024": 140000, "2025": 33000, "2026_ytd": 61000, "2026_proj": 177000},
        "situation": "Quiet account. Scott Shepard drives volume, trending up, revenue capture 1.27x territory average (complex, valuable cases). Metastasis-weighted with little epilepsy work. Single-surgeon dependent; claims undercount (1 LITT claims vs 10 logged).",
        "surgeons": [("Scott Shepard", 8), ("Eric Quach", 1), ("Willard Kasoff", 1)],
        "referrers": [("Scott Shepard", "Metastasis/Primary", 3), ("Stephanie Weiss", "Metastasis", 3),
                      ("Avani Shah", "Epilepsy", 1), ("Curtis Miyamoto", "Primary", 1)],
        "reservoirs": {"Mets": (9, 186), "Radiation necrosis": (0, 5),
                       "Intractable epilepsy": (14, 288), "Recurrent GBM": (0, 1)},
        "user_targets": ["Scott Shepard", "Kadir Erkmen", "Willard S Kasoff", "Eric T Quach"],
        "epilepsy_referrers": [("Mercedes Jacobson", 249), ("Molly C Cincotta", 3)],
        "necrosis_referrers": [("Steven W Hwang", 10)],
        "business_potential_yr": 116260, "incremental_cases": 5, "win": "Medium",
    },
    {
        "rank": 16, "name": "Rochester General", "acronym": "ROC", "system": "Rochester Regional Health",
        "class": "Installed", "posture": "Grow / verify", "platform": [NEUROBLATE],
        "cases_logged": 5, "trend": "Up",
        "net_sales_by_year": {"2024": 55000, "2025": 0, "2026_ytd": 0, "2026_proj": 0},
        "situation": "Kimmell is our user, primarily tumor. Workflow is the constraint (bolt in OR, transport to GE scanner, close in recovery). Probe restock 0.75 (lowest), revenue capture 0.62x (lowest). Site-identity data issues.",
        "surgeons": [("Kristopher Kimmell", 5)],
        "referrers": [("Ben Onderdonk", "Metastasis", 1), ("Jeffrey Haynes", "Metastasis", 1),
                      ("Khusraw Sabit", "Metastasis", 1)],
        "reservoirs": {"Mets": (6, 126)},
        "user_targets": ["Melissa A Lopresti", "Vincent N Nguyen", "Kevin A Walter", "Patrick J Reid"],
        "epilepsy_referrers": [],
        "necrosis_referrers": [("Lon K Baratz", 1)],
        "business_potential_yr": 0, "incremental_cases": 0, "win": "Long-horizon",
    },
    {
        "rank": 17, "name": "Upstate University Hospital", "acronym": "SUNY", "system": "SUNY Upstate Medical University",
        "class": "Contested", "posture": "Rebuild", "platform": [NEUROBLATE, VISUALASE],
        "cases_logged": 3, "trend": "Down",
        "net_sales_by_year": {"2024": 0, "2025": 31000, "2026_ytd": 57000, "2026_proj": 57000},
        "situation": "Lost Zulma Tovar-Spinoza (left for South Carolina); volume fell with her. Knudsen is new (first epilepsy case in March) — effectively restarting. No tumor work. Sits on ~1,073 intractable-epilepsy patients, one of the largest DRE pools in the territory. Miller carries 19 epilepsy cranis.",
        "surgeons": [("Zulma Tovar Spinoza", 2), ("Kathleen Knudson", 1)],
        "referrers": [("Grahame Gould", "Metastasis", 1), ("Katherine Gutchess", "Epilepsy", 1),
                      ("Zulma Tovar Spinoza", "Epilepsy", 1)],
        "reservoirs": {"Mets": (116, 2314), "Radiation necrosis": (4, 78),
                       "Intractable epilepsy": (54, 1073), "Recurrent GBM": (0, 9)},
        "user_targets": ["Grahame Gould", "Ryan Miller", "Lawrence S Chin", "Harish Babu"],
        "epilepsy_referrers": [("Shahram Izadyar", 320), ("Xiangping Zhou", 242), ("Carlos F Muniz", 171)],
        "necrosis_referrers": [("Timothy M Beutler", 123), ("Harish Babu", 119), ("Meahgan Lefevre", 82)],
        "business_potential_yr": 0, "incremental_cases": 0, "win": "Long-horizon",
    },
    {
        "rank": 18, "name": "Weill Cornell", "acronym": "CORN", "system": "NewYork-Presbyterian",
        "class": "Installed", "posture": "Build", "platform": [NEUROBLATE],
        "cases_logged": 2, "trend": "Flat",
        "net_sales_by_year": {"2024": 28000, "2025": 0, "2026_ytd": 0, "2026_proj": 0},
        "situation": "Quiet account with two logged cases; claims show zero LITT against our two. Real opening is external: Mark Souweidane (MSK) wants to start a program at Cornell, which would convert a dormant account into a surgeon-led build.",
        "surgeons": [("Rohan Ramakrishna", 1), ("Theodore Schwartz", 1)],
        "referrers": [("Eric B. Geller", "Epilepsy", 1)],
        "reservoirs": {"Mets": (18, 350), "Radiation necrosis": (1, 22), "Intractable epilepsy": (9, 175)},
        "user_targets": ["Justin Schwarz", "Michael Kaplitt", "Philip Stieg", "Rohan Ramakrishna"],
        "epilepsy_referrers": [("Steven Karceski", 104), ("Padmaja Kandula", 62)],
        "necrosis_referrers": [("Baoqing Li", 4), ("Caitlin Hoffman", 4), ("Steven Karceski", 2)],
        "business_potential_yr": 0, "incremental_cases": 0, "win": "Long-horizon",
    },
]

# Competitive leakage: claims LITT volume not ours (3-yr)
COMPETITIVE_LEAKAGE = [
    ("Boston Children's", 112, 0, 112, "Win-back", UNVERIFIED),
    ("Brigham & Women's", 102, 23, 79, "In-account defense", CLEARPOINT),
    ("Dartmouth-Hitchcock", 45, 0, 45, "Displacement", UNVERIFIED),
    ("Hackensack University MC", 31, 0, 31, "Displacement", VISUALASE),
    ("Penn Medicine", 27, 0, 27, "Displacement", UNVERIFIED),
    ("Rhode Island Hospital / Brown", 18, 0, 18, "Displacement", UNVERIFIED),
    ("Jefferson Health", 14, 0, 14, "Displacement", VISUALASE),
    ("Mount Sinai", 12, 0, 12, "In-account defense", UNVERIFIED),
    ("Beth Israel Deaconess", 14, 4, 10, "In-account defense", VISUALASE),
    ("Northwell Health", 9, 0, 9, "Displacement", VISUALASE),
]

# Prospects & landscape: programs outside installed base
PROSPECTS = [
    ("Jefferson Health", "Chengyuan (Chen) Wu", 13, 44, 39, 9223, VISUALASE),
    ("Northwell Health", "Ashesh Mehta", 9, 16, 12, 16112, VISUALASE),
    ("Albany Med", "Matthew Adamo", 10, 18, 13, 20150, UNVERIFIED),
    ("Saint Joseph's Health", "Nader Delavari", 9, 0, 0, 13, UNVERIFIED),
    ("MaineHealth (Maine Medical)", "Anand Rughani", 8, 0, 0, 6831, UNVERIFIED),
    ("Rutgers / RWJBarnabas", "Robert Gross", 3, 4, 2, 0, UNVERIFIED),
    ("Atlantic Health", "Ronald Benitez", 3, 9, 5, 2441, UNVERIFIED),
    ("Buffalo / UBMD", "Jonathan Riley", 3, 6, 5, 80, UNVERIFIED),
    ("Capital Health", "Navid Redjal", 3, 1, 1, 732, UNVERIFIED),
    ("Hartford Healthcare", "Mohamad Khaled", 1, 11, 11, 895, UNVERIFIED),
    ("Cooper University", "— none —", 0, 0, 0, 559, "None (Confirmed)"),
]

# Top user targets with composite opportunity index (COI) from the deck
TOP_USER_TARGETS = [
    ("Scellig S Stone", "Boston Childrens Hospital, Brigham", "Convert", 66, 270, 0, 83.9),
    ("Luke Tomycz", "The Epilepsy Institute of New Jersey", "Convert", 18, 110, 0, 58.2),
    ("Fedor E Panov", "Mount Sinai West, Mount Sinai", "Convert", 8, 118, 0, 56.2),
    ("Saadi Ghatan", "Mount Sinai West, Mount Sinai", "Convert", 4, 118, 0, 54.9),
    ("Han-Chiao I Chen", "Hospital of the University of Pennsylvania", "Convert", 18, 68, 0, 49.5),
    ("Linton T Evans", "Dartmouth Hitchcock Medical Center", "Convert", 34, 0, 2, 48.2),
    ("Anand I Rughani", "MaineHealth Maine Medical Center", "Convert", 5, 0, 0, 47.7),
    ("Rafael A Vega", "Beth Israel Deaconess Medical Center", "Grow", 2, 0, 6, 46.5),
    ("Matthew Adamo", "Albany Medical Center", "Convert", 10, 34, 0, 45.7),
    ("Nathan E Simmons", "Dartmouth Hitchcock Medical Center", "Convert", 4, 0, 8, 38.2),
]
