(() => {
  'use strict';
  const esc = value => String(value == null ? '' : value).replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const placeholderImage = 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%22360%22 height=%22240%22 viewBox=%220 0 360 240%22%3E%3Crect width=%22360%22 height=%22240%22 rx=%2220%22 fill=%22%23ffffff%22 fill-opacity=%22.78%22 stroke=%22%23b9c9d1%22 stroke-width=%222%22 stroke-dasharray=%228 8%22/%3E%3Ctext x=%22180%22 y=%22112%22 text-anchor=%22middle%22 font-family=%22Arial%22 font-size=%2218%22 font-weight=%22700%22 fill=%22%2353657A%22%3EADD PRODUCT IMAGE%3C/text%3E%3Ctext x=%22180%22 y=%22142%22 text-anchor=%22middle%22 font-family=%22Arial%22 font-size=%2212%22 fill=%22%23788794%22%3ETransparent PNG recommended%3C/text%3E%3C/svg%3E';
  const markFor = profile => Object.prototype.hasOwnProperty.call(profile, 'brandMark') ? profile.brandMark : '®';
  function legalName(profile) {
    if (profile.brandName && profile.genericName) return `${profile.brandName}${markFor(profile)} (${String(profile.genericName).toLowerCase()})`;
    return profile.genericName ? `${profile.genericName}${profile.strength ? ', ' + profile.strength : ''}` : '[[ADD APPROVED PRODUCT NAME]]';
  }
  function legalRow(profile) {
    const name = legalName(profile);
    const brand = profile.brandName || '';
    if (!brand) return `<tr data-regulatory-legal-name="generic" data-builder-legal-name-compact="true"><td class="pad" style="padding:6px 28px 8px;background:#FFFFFF;"><table role="presentation" width="100%" data-builder-style-box="legal-name" bgcolor="#F3F7F4" style="background:#F3F7F4;border:1px solid #DCE8E0;border-radius:12px;"><tr><td style="padding:8px 13px 7px;"><div style="font-family:Arial,Helvetica,sans-serif;font-size:20px;line-height:24px;font-weight:800;color:${esc(profile.primaryColor || '#277E82')};">${esc(name)}</div><div style="font-family:Arial,Helvetica,sans-serif;font-size:11px;line-height:15px;font-weight:700;color:#667787;">${esc([profile.strength, profile.dosageForm].filter(Boolean).join(' '))}</div></td></tr></table></td></tr>`;
    const mark = markFor(profile), markHtml = mark ? `<sup style="font-size:11px;line-height:1;vertical-align:super;">${esc(mark)}</sup>` : '';
    return `<tr data-regulatory-legal-name="${esc(brand)}" data-builder-legal-name-compact="true"><td class="pad" style="padding:6px 28px 8px;background:#FFFFFF;"><table role="presentation" width="100%" data-builder-style-box="legal-name" bgcolor="#F3F7F4" style="background:#F3F7F4;border:1px solid #DCE8E0;border-radius:12px;"><tr><td style="padding:8px 13px 7px;"><a href="${esc(profile.productUrl || profile.piUrl || '#')}" aria-label="${esc(name)} product website" style="display:block;color:#173F34;text-decoration:none;"><span style="font-family:Arial,Helvetica,sans-serif;font-size:23px;line-height:27px;font-weight:800;color:${esc(profile.primaryColor || '#249647')};">${esc(brand)}${markHtml}</span><span style="font-family:Arial,Helvetica,sans-serif;font-size:14px;line-height:20px;font-weight:700;color:#253449;"> (${esc(String(profile.genericName || '').toLowerCase())})</span><span style="display:block;font-family:Arial,Helvetica,sans-serif;font-size:11px;line-height:15px;font-weight:700;color:#667787;">${esc([profile.strength, profile.dosageForm].filter(Boolean).join(' '))}</span></a></td></tr></table></td></tr>`;
  }
  function button(label, url, color, width) {
    return `<!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="${esc(url)}" style="height:46px;v-text-anchor:middle;width:${width}px;" arcsize="14%" stroke="f" fillcolor="${esc(color)}"><w:anchorlock/><center style="color:#ffffff;font-family:Arial,sans-serif;font-size:15px;font-weight:bold;">${esc(label)}</center></v:roundrect><![endif]--><!--[if !mso]><!--><a href="${esc(url)}" style="background:${esc(color)};border-radius:7px;color:#ffffff;display:inline-block;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:700;line-height:46px;text-align:center;width:${width}px;-webkit-text-size-adjust:none;">${esc(label)}</a><!--<![endif]-->`;
  }
  window.ALEMBIC_BUILD_BLANK_EMAIL = function(profile = {}) {
    const primary = profile.primaryColor || '#249647';
    const secondary = profile.secondaryColor || '#0878C9';
    const product = profile.brandName || profile.name || 'Your Product';
    const productImage = profile.productImage || placeholderImage;
    const imagePlaceholder = profile.productImage ? '' : ' data-builder-placeholder-image="true"';
    const piUrl = profile.piUrl || '[[ADD_APPROVED_PI_URL]]';
    const indication = profile.indication || '[[ADD APPROVED INDICATION]]';
    const isi = profile.isi || '[[ADD APPROVED IMPORTANT SAFETY INFORMATION]]';
    const footer = profile.footer || '[[ADD APPROVED COMPANY AND AUDIENCE FOOTER]]';
    const styles = `html,body{margin:0!important;padding:0!important;width:100%!important;background:#F1F4F5;}table{border-spacing:0;border-collapse:collapse;}img{border:0;line-height:100%;outline:none;text-decoration:none;}a{text-decoration:none;}@media screen and (max-width:600px){.shell{width:100%!important;}.pad{padding-left:20px!important;padding-right:20px!important;}.stack{display:block!important;width:100%!important;max-width:100%!important;box-sizing:border-box!important;}.mob-center{text-align:center!important;}.mob-top{padding-top:16px!important;}.hero-copy{padding-right:22px!important;}.card-gap{height:10px!important;display:block!important;}.h1{font-size:31px!important;line-height:36px!important;}.h2{font-size:24px!important;line-height:30px!important;}}`;
    return `<!doctype html><html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><meta name="supported-color-schemes" content="light"><title>${esc(product)} pharmacy email</title><!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml><![endif]--><style>${styles}</style></head><body style="margin:0;padding:0;background:#F1F4F5;"><div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;mso-hide:all;">Add a concise preview of this pharmacy communication.&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;background:#F1F4F5;"><tr><td align="center" style="padding:22px 10px;"><table role="presentation" class="shell" width="600" cellspacing="0" cellpadding="0" border="0" style="width:600px;max-width:600px;background:#FFFFFF;">
    <tr><td class="pad" style="padding:14px 28px;background:#173F34;"><table role="presentation" width="100%"><tr><td style="font-family:Arial,Helvetica,sans-serif;color:#FFFFFF;font-size:14px;line-height:20px;font-weight:800;letter-spacing:.4px;">ALEMBIC PHARMACEUTICALS</td><td align="right" style="font-family:Arial,Helvetica,sans-serif;color:#DCE9E4;font-size:11px;line-height:16px;font-weight:700;">PHARMACY COMMUNICATION</td></tr></table></td></tr>
    <tr><td style="height:4px;font-size:0;line-height:0;background:${esc(primary)};">&nbsp;</td></tr><tr><td style="height:3px;font-size:0;line-height:0;background:${esc(secondary)};">&nbsp;</td></tr>
    ${legalRow(profile)}
    <tr data-builder-custom-label="Hero"><td class="pad" style="padding:12px 28px 22px;background:#FFFFFF;"><table role="presentation" width="100%" data-builder-style-box="hero" bgcolor="#E6F3EA" style="background-color:rgba(216,240,224,.88);border:1px solid #C9E3D1;border-radius:20px;"><tr><td class="stack hero-copy mob-center" width="60%" valign="middle" style="padding:28px 8px 28px 26px;"><div style="font-family:Arial,Helvetica,sans-serif;font-size:11px;line-height:16px;font-weight:800;letter-spacing:1.1px;color:${esc(primary)};text-transform:uppercase;">PHARMACY UPDATE</div><div class="h1" style="font-family:Arial,Helvetica,sans-serif;font-size:37px;line-height:42px;font-weight:800;color:#173F34;padding-top:8px;">Add a clear, useful headline</div><div style="font-family:Arial,Helvetica,sans-serif;font-size:16px;line-height:24px;color:#435768;padding-top:10px;">Add a short subheadline that tells the pharmacy exactly why this communication matters.</div><div style="padding-top:18px;text-align:center;">${button('Primary Call to Action', 'https://example.com/', secondary, 210)}</div></td><td class="stack mob-center mob-top" width="40%" align="center" valign="middle" style="padding:22px 22px 22px 10px;"><img src="${productImage}"${imagePlaceholder} data-builder-asset-slot="Product" width="190" alt="${esc(product)} product image" style="display:block;width:190px;max-width:100%;height:auto;margin:0 auto;"></td></tr></table></td></tr>
    <tr data-builder-custom-label="Three key points"><td class="pad" style="padding:0 28px 20px;background:#FFFFFF;"><table role="presentation" width="100%" style="border-collapse:separate;border-spacing:0;"><tr><td class="stack" width="32%" valign="top" style="background:#F0F8F2;border-top:4px solid ${esc(primary)};padding:18px 15px;"><div style="font-family:Arial,Helvetica,sans-serif;font-size:17px;line-height:22px;font-weight:800;color:#173F34;">Key point one</div><div style="font-family:Arial,Helvetica,sans-serif;font-size:13px;line-height:20px;color:#53657A;padding-top:7px;">Add one concise, source-supported pharmacy takeaway.</div></td><td class="card-gap" width="2%" style="font-size:0;line-height:0;">&nbsp;</td><td class="stack" width="32%" valign="top" style="background:#F3F7FB;border-top:4px solid ${esc(secondary)};padding:18px 15px;"><div style="font-family:Arial,Helvetica,sans-serif;font-size:17px;line-height:22px;font-weight:800;color:#173F34;">Key point two</div><div style="font-family:Arial,Helvetica,sans-serif;font-size:13px;line-height:20px;color:#53657A;padding-top:7px;">Keep the supporting copy easy to scan and understand.</div></td><td class="card-gap" width="2%" style="font-size:0;line-height:0;">&nbsp;</td><td class="stack" width="32%" valign="top" style="background:#F5F7F7;border-top:4px solid #277E82;padding:18px 15px;"><div style="font-family:Arial,Helvetica,sans-serif;font-size:17px;line-height:22px;font-weight:800;color:#173F34;">Key point three</div><div style="font-family:Arial,Helvetica,sans-serif;font-size:13px;line-height:20px;color:#53657A;padding-top:7px;">Use approved language and include any necessary qualifier.</div></td></tr></table></td></tr>
    <tr data-builder-custom-label="Data image and explanation"><td class="pad" style="padding:0 28px 20px;background:#FFFFFF;"><table role="presentation" width="100%" data-builder-style-box="data" bgcolor="#F7F9FA" style="background:#F7F9FA;border:1px solid #DFE7EA;border-radius:17px;"><tr><td style="padding:21px 20px 12px;"><div class="h2" style="font-family:Arial,Helvetica,sans-serif;font-size:27px;line-height:33px;font-weight:800;color:#173F34;text-align:center;">Add a data headline</div></td></tr><tr><td align="center" style="padding:0 20px;"><img src="${placeholderImage}" data-builder-placeholder-image="true" data-builder-asset-slot="Clinical" width="500" alt="Replace with an approved graph or data image" style="display:block;width:500px;max-width:100%;height:auto;margin:0 auto;"></td></tr><tr><td style="padding:15px 20px 9px;"><div data-builder-data-explanation="true" style="font-family:Arial,Helvetica,sans-serif;font-size:14px;line-height:22px;color:#253449;"><strong>What this means:</strong> Add a concise explanation of the data and why it is relevant to the pharmacy audience.</div></td></tr><tr><td style="padding:0 20px 20px;"><div data-builder-data-source="true" style="font-family:Arial,Helvetica,sans-serif;font-size:10.5px;line-height:16px;color:#748390;">Source: [[ADD APPROVED DATA SOURCE OR REFERENCE]]</div></td></tr></table></td></tr>
    <tr data-builder-custom-label="How to order"><td class="pad" style="padding:0 28px 20px;background:#FFFFFF;"><table role="presentation" width="100%" data-builder-style-box="ordering" bgcolor="#F3F7FB" style="background:#F3F7FB;border:1px solid #D8E4EC;border-radius:16px;"><tr><td style="padding:20px;"><div style="font-family:Arial,Helvetica,sans-serif;font-size:11px;line-height:16px;font-weight:800;letter-spacing:1px;color:${esc(primary)};text-transform:uppercase;">HOW TO ORDER</div><div style="font-family:Arial,Helvetica,sans-serif;font-size:22px;line-height:28px;font-weight:800;color:#173F34;padding-top:5px;">Ordering information</div><table role="presentation" width="100%" style="font-family:Arial,Helvetica,sans-serif;font-size:13.5px;line-height:20px;color:#253449;margin-top:11px;"><tr><td width="38%" style="padding:5px 0;color:#6A7886;">Wholesaler or distributor</td><td style="padding:5px 0;font-weight:700;">[[INSERT INFORMATION]]</td></tr><tr><td style="padding:5px 0;color:#6A7886;">Item or catalog number</td><td style="padding:5px 0;font-weight:700;">[[INSERT INFORMATION]]</td></tr><tr><td style="padding:5px 0;color:#6A7886;">Ordering link or contact</td><td style="padding:5px 0;font-weight:700;">[[INSERT INFORMATION]]</td></tr><tr><td style="padding:5px 0;color:#6A7886;">Availability notes</td><td style="padding:5px 0;font-weight:700;">[[INSERT INFORMATION]]</td></tr></table></td></tr></table></td></tr>
    <tr data-builder-custom-label="Patient savings"><td class="pad" style="padding:0 28px 20px;background:#FFFFFF;"><table role="presentation" width="100%" data-builder-style-box="savings" bgcolor="#F3FAF5" style="background:#F3FAF5;border:1px solid #D8EBDD;border-radius:16px;"><tr><td class="stack" valign="middle" style="padding:19px 20px;"><div style="font-family:Arial,Helvetica,sans-serif;font-size:19px;line-height:25px;font-weight:800;color:#173F34;">Patient access and savings</div><div style="font-family:Arial,Helvetica,sans-serif;font-size:13.5px;line-height:21px;color:#53657A;padding-top:6px;">[[ADD APPROVED SAVINGS OR ACCESS INFORMATION, INCLUDING REQUIRED ELIGIBILITY LANGUAGE]]</div></td><td class="stack mob-center" width="165" align="center" valign="middle" style="padding:19px 20px;">${button('View Information', 'https://example.com/', primary, 145)}</td></tr></table></td></tr>
    <tr data-builder-custom-label="Secondary call to action"><td class="pad" align="center" style="padding:0 28px 24px;background:#FFFFFF;text-align:center;"><div style="font-family:Arial,Helvetica,sans-serif;font-size:19px;line-height:25px;font-weight:800;color:#173F34;padding-bottom:12px;">Add a final practical next step</div>${button('Secondary Call to Action', 'https://example.com/', secondary, 225)}</td></tr>
    <tr data-regulatory-section="indication"><td class="pad" style="padding:19px 28px;background:#FFFFFF;border-top:1px solid #DDE6E8;"><div style="font-family:Arial,Helvetica,sans-serif;font-size:12px;line-height:17px;font-weight:800;letter-spacing:.6px;color:${esc(primary)};padding-bottom:6px;">INDICATION</div><div style="font-family:Arial,Helvetica,sans-serif;font-size:13px;line-height:20px;color:#253449;">${esc(indication)}</div></td></tr>
    <tr data-regulatory-section="isi"><td class="pad" style="padding:0 28px 22px;background:#FFFFFF;"><table role="presentation" width="100%" bgcolor="#FFF5F4" style="background:#FFF5F4;border:1px solid #F0D8D5;border-radius:16px;"><tr><td style="padding:19px 20px 7px;"><div style="font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:20px;font-weight:800;color:#9E4242;">IMPORTANT SAFETY INFORMATION</div></td></tr><tr><td style="padding:5px 20px 18px;font-family:Arial,Helvetica,sans-serif;font-size:12.5px;line-height:19px;color:#253449;">${esc(isi)}</td></tr></table></td></tr>
    <tr><td align="center" class="pad" style="padding:0 28px 22px;background:#FFFFFF;text-align:center;">${button('Review Prescribing Information', piUrl, secondary, 238)}</td></tr>
    <tr data-builder-custom-label="Company and social"><td class="pad" style="padding:19px 28px;background:#F4F7F6;border-top:1px solid #DDE6E8;"><table role="presentation" width="100%"><tr><td class="stack mob-center" style="font-family:Arial,Helvetica,sans-serif;font-size:12px;line-height:19px;color:#53657A;"><strong style="color:#173F34;">Alembic Pharmaceuticals, Inc.</strong><br>750 Route 202, Bridgewater, NJ 08807<br><a href="https://www.alembicusa.com/" style="color:${esc(secondary)};font-weight:700;">alembicusa.com</a></td><td class="stack mob-center mob-top" align="right" valign="middle" style="font-family:Arial,Helvetica,sans-serif;font-size:12px;line-height:20px;"><a href="https://www.linkedin.com/company/alembic-pharmaceuticals-limited/" style="display:inline-block;color:${esc(secondary)};font-weight:800;padding:8px;">LinkedIn</a><a href="https://www.alembicusa.com/" style="display:inline-block;color:${esc(primary)};font-weight:800;padding:8px;">Website</a></td></tr></table></td></tr>
    <tr data-regulatory-section="footer"><td class="pad" style="padding:16px 28px 21px;background:#173F34;font-family:Arial,Helvetica,sans-serif;font-size:10.5px;line-height:16px;color:#DDE8E4;text-align:center;">${esc(footer)}<br>[[SENDING PARTNER: INSERT REQUIRED UNSUBSCRIBE AND PERMISSION LANGUAGE]]</td></tr>
    </table></td></tr></table></body></html>`;
  };
})();
