(() => {
  'use strict';
  const templates = window.PIVYA_TEMPLATES || [];
  const source = templates.find(t => t.id === 'email2');
  if (!source || templates.some(t => t.id === 'email7')) return;

  const pharmacyWhyCard = `<tr><td class="pad" style="padding:14px 28px 20px;background:#FFFFFF;"><table role="presentation" width="100%" style="background:#EAF6EE;border:1px solid #CFE8D7;border-radius:18px;"><tr><td style="padding:19px 20px 18px;"><div style="font-size:11px;line-height:16px;font-weight:800;letter-spacing:1.1px;color:#249647;text-transform:uppercase;padding-bottom:13px;">WHY PIVYA</div><table role="presentation" width="100%"><tr><td width="30" valign="top" style="padding:1px 10px 11px 0;"><span style="display:inline-block;width:22px;height:22px;border-radius:11px;background:#249647;color:#FFFFFF;font-size:13px;line-height:22px;font-weight:800;text-align:center;">✓</span></td><td valign="top" style="padding:0 0 11px;font-size:14.5px;line-height:21px;color:#253449;">An FDA-approved oral antibacterial treatment option for appropriate adult women with uUTI caused by susceptible isolates</td></tr><tr><td width="30" valign="top" style="padding:1px 10px 11px 0;"><span style="display:inline-block;width:22px;height:22px;border-radius:11px;background:#0878C9;color:#FFFFFF;font-size:13px;line-height:22px;font-weight:800;text-align:center;">✓</span></td><td valign="top" style="padding:0 0 11px;font-size:14.5px;line-height:21px;color:#253449;">Indicated for susceptible <em>E. coli</em>, <em>P. mirabilis</em>, and <em>S. saprophyticus</em></td></tr><tr><td width="30" valign="top" style="padding:1px 10px 11px 0;"><span style="display:inline-block;width:22px;height:22px;border-radius:11px;background:#249647;color:#FFFFFF;font-size:13px;line-height:22px;font-weight:800;text-align:center;">✓</span></td><td valign="top" style="padding:0 0 11px;font-size:14.5px;line-height:21px;color:#253449;">Qualified Infectious Disease Product (QIDP) designation by the FDA</td></tr><tr><td width="30" valign="top" style="padding:1px 10px 11px 0;"><span style="display:inline-block;width:22px;height:22px;border-radius:11px;background:#0878C9;color:#FFFFFF;font-size:13px;line-height:22px;font-weight:800;text-align:center;">✓</span></td><td valign="top" style="padding:0 0 11px;font-size:14.5px;line-height:21px;color:#253449;">Patient access resources include the PIVYA Savings Card and GoodRx; eligibility and terms apply</td></tr><tr><td width="30" valign="top" style="padding:1px 10px 0 0;"><span style="display:inline-block;width:22px;height:22px;border-radius:11px;background:#249647;color:#FFFFFF;font-size:13px;line-height:22px;font-weight:800;text-align:center;">✓</span></td><td valign="top" style="padding:0;font-size:14.5px;line-height:21px;color:#253449;">Supplied in a slim blister-pack format</td></tr></table></td></tr></table></td></tr>`;

  const ordering = `<tr><td class="pad" style="padding:6px 28px 20px;background:#FFFFFF;"><table role="presentation" width="100%" style="background:#F5F8FB;border:1px solid #DCE5EC;border-radius:16px;"><tr><td style="padding:19px 18px 9px;"><div style="font-size:11px;line-height:16px;font-weight:800;letter-spacing:1px;color:#249647;text-transform:uppercase;">PHARMACY ORDERING INFORMATION</div><div style="font-size:21px;line-height:27px;font-weight:700;color:#253449;padding-top:4px;">Order PIVYA through Cencora</div></td></tr><tr><td style="padding:5px 18px 18px;"><table role="presentation" width="100%" style="font-size:13.5px;line-height:20px;color:#253449;"><tr><td width="38%" style="padding:5px 0;color:#6A7886;">Product</td><td style="padding:5px 0;font-weight:700;">PIVYA 185 mg tablets</td></tr><tr><td style="padding:5px 0;color:#6A7886;">Distributor</td><td style="padding:5px 0;font-weight:700;">Cencora</td></tr><tr><td style="padding:9px 0;color:#6A7886;">Entry / SAP #</td><td style="padding:9px 0;"><span style="display:inline-block;background:#0878C9;color:#FFFFFF;border-radius:999px;padding:7px 14px;font-size:15px;line-height:18px;font-weight:800;letter-spacing:.5px;">10307184</span></td></tr><tr><td style="padding:5px 0;color:#6A7886;">NDC</td><td style="padding:5px 0;font-weight:700;">62332-966-09</td></tr></table></td></tr></table></td></tr>`;

  const access = `<tr><td class="pad" style="padding:0 28px 20px;background:#FFFFFF;"><table role="presentation" width="100%" style="background:#F3FAF5;border:1px solid #DCEDE1;border-radius:14px;"><tr><td style="padding:17px 18px 10px;"><div style="font-size:18px;line-height:23px;font-weight:700;color:#249647;">Patient access resources</div><div style="font-size:13.5px;line-height:20px;color:#253449;padding-top:5px;">PIVYA patient-access resources include the PIVYA Savings Card and GoodRx. Eligibility, pricing, terms and conditions apply.</div></td></tr><tr><td align="center" style="padding:0 18px 17px;text-align:center;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center"><tr><td style="padding-right:8px;"><!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="https://pivya.com/saving-card.aspx" style="height:42px;v-text-anchor:middle;width:138px;" arcsize="14%" stroke="f" fillcolor="#249647"><w:anchorlock/><center style="color:#ffffff;font-family:Arial,sans-serif;font-size:14px;font-weight:bold;">Savings Card</center></v:roundrect><![endif]--><!--[if !mso]><!--><a href="https://pivya.com/saving-card.aspx" style="background:#249647;border-radius:6px;color:#FFFFFF;display:inline-block;font-family:Arial,sans-serif;font-size:14px;font-weight:700;line-height:42px;text-align:center;width:138px;">Savings Card</a><!--<![endif]--></td><td><!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="https://www.goodrx.com/pivya" style="height:42px;v-text-anchor:middle;width:112px;" arcsize="14%" stroke="f" fillcolor="#0878C9"><w:anchorlock/><center style="color:#ffffff;font-family:Arial,sans-serif;font-size:14px;font-weight:bold;">GoodRx</center></v:roundrect><![endif]--><!--[if !mso]><!--><a href="https://www.goodrx.com/pivya" style="background:#0878C9;border-radius:6px;color:#FFFFFF;display:inline-block;font-family:Arial,sans-serif;font-size:14px;font-weight:700;line-height:42px;text-align:center;width:112px;">GoodRx</a><!--<![endif]--></td></tr></table></td></tr></table></td></tr>`;

  let html = source.html
    .replace(/<title>[\s\S]*?<\/title>/i, '<title>Why You Need PIVYA In Your Pharmacy</title>')
    .replace('HEALTHCARE PROFESSIONAL<br>COMMUNICATION', 'PHARMACY PARTNER<br>COMMUNICATION')
    .replace('PIVYA | APPROVED IN 2024', 'PIVYA | PHARMACY PARTNER COMMUNICATION')
    .replace('The first FDA-approved antibiotic for uUTIs in <span style="color:#0878C9;">20 years</span><sup style="font-size:20px;">2</sup>', 'Why You Need <span style="color:#0878C9;">PIVYA</span> In Your Pharmacy')
    .replace('<div class="bodycopy" style="font-size:16px;line-height:25px;color:#53657A;padding-top:14px;max-width:530px;">PIVYA was FDA approved in 2024 for the treatment of adult women with uUTI caused by susceptible <em>E. coli</em>, <em>P. mirabilis</em>, and <em>S. saprophyticus</em>. Pivmecillinam has been used clinically outside the United States for more than 40 years.<sup>2</sup></div>', '')
    .replace(/<div style="padding-top:18px;padding-bottom:8px;">[\s\S]*?<\/div>\s*<\/td><\/tr>/, '</td></tr>')
    .replace('A new U.S. option with decades of experience', 'The first FDA-approved antibiotic for uUTIs in approximately 20 years<sup>2</sup>')
    .replace('PIVYA is a penicillin-class antibacterial for female patients 18 years of age and older with uUTI caused by susceptible isolates of <em>E. coli</em>, <em>P. mirabilis</em>, and <em>S. saprophyticus</em>. It was approved by the FDA in 2024 and has been used clinically outside the United States for more than four decades.', 'In 2024, PIVYA became the first FDA-approved antibiotic for uUTIs in approximately 20 years. PIVYA is indicated for adult women with uUTI caused by susceptible isolates of <em>E. coli</em>, <em>P. mirabilis</em>, and <em>S. saprophyticus</em>.<sup>1,2</sup>');

  const removeStart = html.indexOf('<tr><td class="pad" style="padding:10px 28px 8px;background:#FFFFFF;"><img src="assets/dosing/approval-and-use-timeline.png"');
  const indicationStart = html.indexOf('<tr><td class="pad" style="padding:18px 28px 18px;background:#FFFFFF;border-top:1px solid #DDE6E8;">');
  if (removeStart !== -1 && indicationStart > removeStart) {
    html = html.slice(0, removeStart) + pharmacyWhyCard + ordering + access + html.slice(indicationStart);
  }

  templates.push({
    id: 'email7',
    name: 'Email 7 · Pharmacy partner ordering',
    product: 'pivya',
    audience: 'Pharmacy',
    filename: 'PIVYA_Pharmacy_Email_07_Cencora_Ordering.html',
    subject: 'Why You Need PIVYA In Your Pharmacy',
    preheader: 'PIVYA product information and Cencora ordering details for pharmacy partners.',
    html
  });
})();
