"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import type { CatalogProduct } from "../lib/catalog";
import { projectStages as stages } from "../lib/ops-data";
import type { StudioProject } from "../lib/ops-data";

export type CustomerRecord = { id: number; name: string; email: string; phone: string; shippingAddress: string; billingAddress: string; totalSpent: number; creditBalance: number; notes: string };
export type PaymentRecord = { id: number; projectId: number; type: string; amount: number; status: string; note: string; createdAt: string };
export type IdeaRecord = { id: number; name: string; email: string; phone: string; person: string; interest: string; occasion: string; budget: string; story: string; source: string; imageKey: string; imageName: string; objectDescription: string; dimensions: string; desiredUse: string; meetingStatus: string; status: string; createdAt: string };
type Tab = "overview" | "ideas" | "projects" | "schedule" | "customers" | "catalog" | "money";
type Modal = "contact" | "schedule" | "payment" | "brief" | "new" | null;

const priorityRank: Record<string, number> = { Rush: 0, Expedited: 1, Standard: 2 };

function daysUntil(date: string) { return Math.ceil((new Date(`${date}T18:00:00`).getTime() - Date.now()) / 86400000); }
function imageFor(project: StudioProject) { const name = project.name.toLowerCase(); if (name.includes("aviation")) return "/assets/airplane-wing-table.webp"; if (name.includes("bar")) return "/assets/toolbox-bourbon-bar.webp"; if (name.includes("sign")) return "/assets/lighted-sign.webp"; if (name.includes("ski")) return "/assets/ski-display.webp"; return "/assets/charcuterie-board.webp"; }

export function OpsDashboard({ initialProjects, initialProducts, initialCustomers, initialPayments, initialInquiries }: { initialProjects: StudioProject[]; initialProducts: CatalogProduct[]; initialCustomers: CustomerRecord[]; initialPayments: PaymentRecord[]; initialInquiries: IdeaRecord[] }) {
  const [projects, setProjects] = useState(initialProjects);
  const [products, setProducts] = useState(initialProducts);
  const [customers] = useState(initialCustomers);
  const [payments, setPayments] = useState(initialPayments);
  const [ideas, setIdeas] = useState(initialInquiries);
  const [selected, setSelected] = useState(initialProjects[0]);
  const [tab, setTab] = useState<Tab>("overview");
  const [modal, setModal] = useState<Modal>(null);
  const [editingProduct, setEditingProduct] = useState<CatalogProduct | null>(null);
  const [saving, setSaving] = useState(false);
  const [toast, setToast] = useState("");

  const rankedProjects = useMemo(() => [...projects].filter((item) => item.status !== "Complete").sort((a, b) => (priorityRank[a.priority ?? "Standard"] - priorityRank[b.priority ?? "Standard"]) || daysUntil(a.due) - daysUntil(b.due)), [projects]);
  const totals = useMemo(() => ({ hours: projects.reduce((sum, item) => sum + item.remaining, 0), value: projects.reduce((sum, item) => sum + item.value, 0), outstanding: projects.reduce((sum, item) => sum + item.value - item.paid, 0), rush: projects.filter((item) => item.priority === "Rush" && item.status !== "Complete").length, blocked: projects.filter((item) => item.blocker).length }), [projects]);

  async function patchProject(project: StudioProject, updates: Partial<StudioProject>, success: string) {
    const updated = { ...project, ...updates };
    setProjects((items) => items.map((item) => item.id === project.id ? updated : item)); setSelected(updated);
    const response = await fetch("/api/projects", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: project.id, ...updates }) });
    setToast(response.ok ? success : "The change could not sync. Try again.");
  }

  async function advance(project: StudioProject) { const nextStatus = stages[Math.min(stages.indexOf(project.status) + 1, stages.length - 1)] || "Build"; await patchProject(project, { status: nextStatus, stage: nextStatus, progress: Math.min(100, project.progress + 12) }, `${project.code} moved to ${nextStatus}.`); }

  async function createProject(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSaving(true); const form = event.currentTarget; const payload = Object.fromEntries(new FormData(form));
    const response = await fetch("/api/projects", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json() as { project?: StudioProject; error?: string }; setSaving(false);
    if (!response.ok || !result.project) { setToast(result.error ?? "Could not add that order."); return; }
    setProjects((items) => [...items, result.project!]); setSelected(result.project); setModal(null); setToast(`${result.project.code} is live on Sam’s board.`); form.reset();
  }

  async function sendCustomerUpdate(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSaving(true); const values = Object.fromEntries(new FormData(event.currentTarget)) as Record<string, string>;
    const response = await fetch("/api/communications", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ projectId: selected.id, channel: values.channel, subject: values.subject, message: values.message }) }); setSaving(false);
    if (!response.ok) { setToast("The note could not be saved."); return; }
    setModal(null); setToast(`Update logged for ${selected.customer}.`);
    if (values.channel === "Email") window.location.href = `mailto:${selected.customerEmail ?? ""}?subject=${encodeURIComponent(values.subject)}&body=${encodeURIComponent(values.message)}`;
    else window.location.href = `sms:${selected.customerPhone ?? ""}?body=${encodeURIComponent(values.message)}`;
  }

  async function adjustSchedule(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)) as Record<string, string>; const dueLabel = new Date(`${values.due}T12:00:00Z`).toLocaleDateString("en-US", { month: "short", day: "numeric", timeZone: "UTC" });
    await patchProject(selected, { due: values.due, dueLabel, blocker: values.blocker, orderStatus: values.approved === "yes" ? "Rescheduled · customer approved" : "Awaiting customer" }, `${selected.code} rescheduled to ${dueLabel}.`); setModal(null);
  }

  async function recordPayment(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSaving(true); const values = Object.fromEntries(new FormData(event.currentTarget)) as Record<string, string>; const amount = Number(values.amount);
    const response = await fetch("/api/payments", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ projectId: selected.id, type: values.type, amount, note: values.note }) }); const result = await response.json() as { payment?: PaymentRecord }; setSaving(false);
    if (!response.ok || !result.payment) { setToast("Could not record that transaction."); return; }
    setPayments((items) => [result.payment!, ...items]); setModal(null); setToast(`${values.type} for $${amount.toFixed(2)} recorded as pending.`);
  }

  async function saveBrief(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSaving(true); const values = Object.fromEntries(new FormData(event.currentTarget));
    const response = await fetch("/api/design-briefs", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ projectId: selected.id, ...values, renderingImage: imageFor(selected), paymentStatus: selected.paymentStatus }) }); setSaving(false);
    if (!response.ok) { setToast("The brief could not be saved."); return; } setToast("Customer design brief saved and ready to send.");
  }

  async function saveProduct(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!editingProduct) return; setSaving(true); const values = Object.fromEntries(new FormData(event.currentTarget));
    const updated: CatalogProduct = { ...editingProduct, name: String(values.name), detail: String(values.detail), price: Number(values.price), inventory: Number(values.inventory), leadTimeDays: Number(values.leadTimeDays), materials: String(values.materials), options: String(values.options).split("\n").map((item) => item.trim()).filter(Boolean), active: values.active === "on" };
    const response = await fetch("/api/catalog", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(updated) }); setSaving(false);
    if (!response.ok) { setToast("The shop item could not be updated."); return; } setProducts((items) => items.map((item) => item.slug === updated.slug ? updated : item)); setEditingProduct(null); setToast(`${updated.name} updated in the shop.`);
  }

  async function markIdea(idea: IdeaRecord, meetingStatus: string) {
    const status = meetingStatus === "scheduled" ? "active" : "contacted";
    const response = await fetch("/api/inquiries", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: idea.id, meetingStatus, status }) });
    if (!response.ok) { setToast("That meeting status could not sync."); return; }
    setIdeas((items) => items.map((item) => item.id === idea.id ? { ...item, meetingStatus, status } : item));
    setToast(`${idea.name}'s idea is marked ${meetingStatus}.`);
  }

  const requestedMeetings = ideas.filter((idea) => idea.meetingStatus === "requested").length;
  const nav: { key: Tab; label: string; icon: string }[] = [{ key: "overview", label: "Command center", icon: "⌂" }, { key: "ideas", label: `Ideas & meetings${requestedMeetings ? ` · ${requestedMeetings}` : ""}`, icon: "✦" }, { key: "projects", label: "Orders & builds", icon: "▦" }, { key: "schedule", label: "Production queue", icon: "◫" }, { key: "customers", label: "Customers", icon: "◎" }, { key: "catalog", label: "Shop manager", icon: "◉" }, { key: "money", label: "Money", icon: "$" }];

  return <main className="ops-shell">
    <aside className="ops-sidebar"><Link className="ops-brand" href="/"><img className="brand-logo small" src="/assets/red-bucket-brand.png" alt="" /><span><b>Red Bucket</b><small>Sam&apos;s studio</small></span></Link><nav>{nav.map((item) => <button className={tab === item.key ? "active" : ""} onClick={() => setTab(item.key)} key={item.key}>{item.icon} <span>{item.label}</span></button>)}</nav><div className="ops-sidebar-bottom"><Link href="/shopboard">Open shop monitor ↗</Link><Link href="/">View storefront ↗</Link><div><span>SR</span><p><b>Sam</b><small>Owner · Maker</small></p></div></div></aside>
    <section className="ops-main"><header className="ops-header"><div><p>{new Date().toLocaleDateString([], { weekday: "long", month: "long", day: "numeric" })}</p><h1>{tab === "overview" ? "Good morning, Sam." : nav.find((item) => item.key === tab)?.label}</h1></div><div><button onClick={() => setModal("new")}>＋ Add order</button><span className="ops-avatar">SR</span></div></header>

      {tab === "overview" && <>{requestedMeetings > 0 && <div className="ops-alert idea-alert"><span>✦</span><div><b>{requestedMeetings} new idea meeting{requestedMeetings === 1 ? "" : "s"} requested.</b><p>Commission requests and Second Act uploads are ready to review.</p></div><button onClick={() => setTab("ideas")}>Review requests →</button></div>}<div className="ops-alert"><span>!</span><div><b>{totals.rush} rush orders are controlling the queue.</b><p>The board ranks paid rush work first, then priority orders, then the nearest standard ship date.</p></div><button onClick={() => setTab("schedule")}>Open live queue →</button></div><div className="ops-metrics"><article><p>Open orders</p><strong>{rankedProjects.length}</strong><span><i className="green" /> {totals.rush} rush</span></article><article><p>Shop time remaining</p><strong>{totals.hours}<small> hrs</small></strong><span><i className="red" /> across active work</span></article><article><p>Money still owed</p><strong>${(totals.outstanding / 1000).toFixed(1)}<small>k</small></strong><span>from ${(totals.value / 1000).toFixed(1)}k booked</span></article><article><p>Needs attention</p><strong>{totals.blocked}</strong><span><i className="gold" /> approvals or materials</span></article></div><Queue projects={rankedProjects.slice(0, 5)} selected={selected} onSelect={setSelected} /><ProjectDetail project={selected} onAdvance={advance} onModal={setModal} /> </>}
      {tab === "ideas" && <><SectionTitle title="Ideas & meeting requests" copy="Every Commission Request and Second Act upload lands here for Sam to review, contact and move into a conversation." /><div className="idea-list">{ideas.length ? ideas.map((idea) => <article className="idea-card" key={idea.id}>{idea.imageKey && <img src={`/api/idea-image?key=${encodeURIComponent(idea.imageKey)}`} alt={`Object uploaded by ${idea.name}`} />}<div className="idea-card-body"><header><div><span>{idea.source === "second-act" ? "The Second Act" : "Commission Request"}</span><h3>{idea.source === "second-act" ? idea.objectDescription : `A gift for ${idea.person}`}</h3></div><em className={idea.meetingStatus}>{idea.meetingStatus}</em></header><div className="idea-facts"><span><small>Interests / direction</small><b>{idea.source === "second-act" ? idea.desiredUse : idea.interest}</b></span><span><small>{idea.source === "second-act" ? "Dimensions" : "Occasion"}</small><b>{idea.source === "second-act" ? idea.dimensions || "Not provided" : idea.occasion}</b></span><span><small>Budget</small><b>{idea.budget}</b></span></div>{idea.story && <p>{idea.story}</p>}<footer><div><b>{idea.name}</b><a href={`mailto:${idea.email}`}>{idea.email}</a><a href={`tel:${idea.phone}`}>{idea.phone}</a></div><div><button onClick={() => { markIdea(idea, "contacted"); window.location.href = `mailto:${idea.email}?subject=${encodeURIComponent("Your Red Bucket idea meeting")}&body=${encodeURIComponent(`Hi ${idea.name}, I reviewed your idea and would love to talk it through. What times work for a quick meeting? — Sam`)}`; }}>Contact to schedule</button><button onClick={() => markIdea(idea, "scheduled")}>Mark scheduled ✓</button></div></footer></div></article>) : <div className="empty-ideas"><b>No meeting requests yet.</b><p>New Commission requests and Second Act uploads will appear here automatically.</p></div>}</div></>}
      {tab === "projects" && <><SectionTitle title="Every order and one-of-one build" copy="Rush orders rise automatically. Open any row to contact the customer, change the date, collect money or prepare the design brief." /><Queue projects={rankedProjects} selected={selected} onSelect={setSelected} /><ProjectDetail project={selected} onAdvance={advance} onModal={setModal} /></>}
      {tab === "schedule" && <><SectionTitle title="Live production queue" copy="The sequence below is the sequence Sam should work. Delivery speed wins first, then the nearest promised ship date." /><div className="priority-legend"><span className="rush">Rush · first bench</span><span className="expedited">Priority · ahead of standard</span><span>Standard · promised date</span></div><Queue projects={rankedProjects} selected={selected} onSelect={setSelected} countdown /><ProjectDetail project={selected} onAdvance={advance} onModal={setModal} /></>}
      {tab === "customers" && <><SectionTitle title="Customer accounts" copy="Contact, shipping, spend, credits and open work in one place. Card details stay with the payment processor and are never stored here." /><div className="customer-table">{customers.map((customer) => { const jobs = projects.filter((project) => project.customerEmail === customer.email); return <article key={customer.id}><div className="customer-avatar">{customer.name.split(" ").map((part) => part[0]).join("").slice(0, 2)}</div><div><h3>{customer.name}</h3><p>{customer.email} · {customer.phone}</p><span>{customer.shippingAddress}</span></div><div><small>Purchases</small><b>{jobs.length}</b></div><div><small>Lifetime spend</small><b>${customer.totalSpent.toLocaleString()}</b></div><div><small>Credit</small><b>${customer.creditBalance.toLocaleString()}</b></div><button onClick={() => { if (jobs[0]) { setSelected(jobs[0]); setModal("contact"); } else window.location.href = `mailto:${customer.email}`; }}>Contact →</button></article>; })}</div></>}
      {tab === "catalog" && <><SectionTitle title="Shop manager" copy="Change what is for sale, price, inventory, materials, options and lead time. Saved changes feed the customer shop." /><div className="catalog-admin">{products.map((product) => <article key={product.slug}><img src={product.image} alt="" /><div><span>{product.category}</span><h3>{product.name}</h3><p>{product.materials}</p></div><div><small>Price</small><b>${product.price}</b></div><div><small>Available</small><b>{product.inventory}</b></div><div><small>Lead time</small><b>{product.leadTimeDays}d</b></div><button onClick={() => setEditingProduct(product)}>Edit →</button></article>)}</div></>}
      {tab === "money" && <><SectionTitle title="Payments, balances, credits and refunds" copy="Track what is owed here. Payment links and completed refunds will execute through Shopify or Stripe once the merchant account is connected." /><div className="money-grid"><article><p>Outstanding</p><strong>${totals.outstanding.toLocaleString()}</strong><span>Across {projects.filter((item) => item.value > item.paid).length} orders</span></article><article><p>Paid</p><strong>${projects.reduce((sum, item) => sum + item.paid, 0).toLocaleString()}</strong><span>Recorded project payments</span></article><article><p>Pending refunds / credits</p><strong>${payments.filter((item) => item.status === "pending").reduce((sum, item) => sum + item.amount, 0).toLocaleString()}</strong><span>{payments.filter((item) => item.status === "pending").length} actions</span></article></div><div className="payment-list">{projects.filter((project) => project.value > project.paid).map((project) => <article key={project.id}><div><small>{project.code}</small><h3>{project.customer}</h3><p>{project.name}</p></div><strong>${(project.value - project.paid).toLocaleString()} due</strong><button onClick={() => { setSelected(project); setModal("payment"); }}>Collect / adjust →</button></article>)}</div></>}
    </section>

    {modal === "contact" && <div className="modal-backdrop"><form className="change-modal" onSubmit={sendCustomerUpdate}><Close onClick={() => setModal(null)} /><p className="eyebrow">Customer update · {selected.code}</p><h2>Keep {selected.customer} in the loop.</h2><div className="contact-card"><b>{selected.customerEmail}</b><span>{selected.customerPhone} · {selected.shippingAddress}</span></div><div className="modal-grid"><label>Send by<select name="channel"><option>Email</option><option>Text message</option></select></label><label>Reason<select onChange={(event) => { const text = event.target.value; const area = document.querySelector<HTMLTextAreaElement>("#customer-message"); if (area) area.value = text; }}><option value="">Choose a template</option><option value={`Hi ${selected.customer}, a material for your ${selected.name} is taking longer than expected. The new projected ship date is ____. Please let me know if that still works for you. — Sam`}>Material delay</option><option value={`Hi ${selected.customer}, your ${selected.name} is ready for approval before we move into fabrication. Reply here with approved or any changes. — Sam`}>Approval needed</option><option value={`Hi ${selected.customer}, quick update: your ${selected.name} is now ${selected.progress}% complete and moving through ${selected.stage}. — Sam`}>Progress update</option></select></label></div><label>Subject<input name="subject" defaultValue={`Update on ${selected.code}: ${selected.name}`} required /></label><label>Message<textarea id="customer-message" name="message" defaultValue={`Hi ${selected.customer}, quick update on your ${selected.name}. It is currently in ${selected.stage}. — Sam`} required /></label><button className="add-bag" disabled={saving}>{saving ? "Saving…" : "Save & open message →"}</button></form></div>}
    {modal === "schedule" && <div className="modal-backdrop"><form className="change-modal" onSubmit={adjustSchedule}><Close onClick={() => setModal(null)} /><p className="eyebrow">Schedule control · {selected.code}</p><h2>Move the promise responsibly.</h2><label>New ship / completion date<input name="due" type="date" defaultValue={selected.due} required /></label><label>Reason for change<textarea name="blocker" defaultValue={selected.blocker} placeholder="Material delay, customer change, shop capacity…" required /></label><label>Customer approval<select name="approved"><option value="no">Not yet · contact customer</option><option value="yes">Yes · customer approved</option></select></label><button className="add-bag">Update production schedule →</button></form></div>}
    {modal === "payment" && <div className="modal-backdrop"><form className="change-modal" onSubmit={recordPayment}><Close onClick={() => setModal(null)} /><p className="eyebrow">Money · {selected.code}</p><h2>Collect, credit or refund.</h2><div className="balance-callout"><span>Project value <b>${selected.value.toLocaleString()}</b></span><span>Paid <b>${selected.paid.toLocaleString()}</b></span><span>Owed <b>${(selected.value - selected.paid).toLocaleString()}</b></span></div><label>Action<select name="type"><option>Payment request</option><option>Refund</option><option>Store credit</option><option>Manual payment</option></select></label><label>Amount<input name="amount" type="number" min="0.01" step=".01" required /></label><label>Internal note<textarea name="note" placeholder="Reason, agreement or reference number" /></label><p className="modal-note">Refunds are logged as pending until the connected payment processor confirms them.</p><button className="add-bag" disabled={saving}>{saving ? "Recording…" : "Record action →"}</button></form></div>}
    {modal === "brief" && <div className="modal-backdrop brief-backdrop"><form className="change-modal design-brief" onSubmit={saveBrief}><Close onClick={() => setModal(null)} /><header><span className="brand-mark">RB</span><div><small>Customer design brief</small><b>{selected.code}</b></div></header><div className="brief-hero"><img src={imageFor(selected)} alt="Project rendering reference" /><span>Rendering / reference</span></div><div className="brief-title"><div><p>Prepared for</p><h2>{selected.customer}</h2></div><div><p>Project</p><h3>{selected.name}</h3></div></div><div className="brief-fields"><label>Dimensions<input name="dimensions" placeholder="W × D × H" required /></label><label>Materials<input name="materials" defaultValue={selected.materialsNeeded} required /></label><label>Customization<textarea name="customization" placeholder="Engraving, colors, branding, lighting, finish…" required /></label><label>Estimated timeline<input name="timeline" defaultValue={`Current target: ${selected.dueLabel}`} required /></label></div><div className="brief-summary"><span>Contact <b>{selected.customerEmail}</b></span><span>Payment <b>{selected.paymentStatus}</b></span><span>Project value <b>${selected.value.toLocaleString()}</b></span></div><div className="brief-actions"><button type="submit" className="add-bag" disabled={saving}>{saving ? "Saving…" : "Save customer brief"}</button><button type="button" onClick={() => window.print()}>Print / save PDF</button><button type="button" onClick={() => window.location.href = `mailto:${selected.customerEmail}?subject=${encodeURIComponent(`${selected.code} design brief`)}&body=${encodeURIComponent(`Hi ${selected.customer}, your Red Bucket design brief for ${selected.name} is ready. Current target: ${selected.dueLabel}. — Sam`)}`}>Email summary</button></div></form></div>}
    {modal === "new" && <div className="modal-backdrop"><form className="change-modal" onSubmit={createProject}><Close onClick={() => setModal(null)} /><p className="eyebrow">New order or build</p><h2>Put it on Sam&apos;s board.</h2><div className="modal-grid"><label>Order code<input name="code" placeholder="RB-260" required /></label><label>Type<select name="kind"><option>Ready to ship</option><option>Semi-custom</option><option>Commission</option></select></label><label>Customer<input name="customer" required /></label><label>Email<input name="customerEmail" type="email" required /></label><label>Phone<input name="customerPhone" required /></label><label>Priority<select name="priority"><option>Standard</option><option>Expedited</option><option>Rush</option></select></label></div><label>Shipping address<input name="shippingAddress" required /></label><label>Project / product<input name="name" placeholder="What are we making?" required /></label><div className="modal-grid"><label>Ship by<input name="due" type="date" required /></label><label>Estimated hours<input name="estimate" type="number" min="0" step=".5" /></label><label>Order value<input name="value" type="number" min="0" /></label><label>Payment status<select name="paymentStatus"><option>Paid</option><option>Deposit paid</option><option>Payment due</option></select></label></div><label>Materials needed<textarea name="materialsNeeded" /></label><button className="add-bag" disabled={saving}>{saving ? "Adding…" : "Add to live board →"}</button></form></div>}
    {editingProduct && <div className="modal-backdrop"><form className="change-modal" onSubmit={saveProduct}><Close onClick={() => setEditingProduct(null)} /><p className="eyebrow">Shop manager</p><h2>Edit {editingProduct.name}</h2><label>Product name<input name="name" defaultValue={editingProduct.name} required /></label><label>Customer-facing description<input name="detail" defaultValue={editingProduct.detail} required /></label><div className="modal-grid"><label>Base price<input name="price" type="number" min="0" defaultValue={editingProduct.price} required /></label><label>Available quantity<input name="inventory" type="number" min="0" defaultValue={editingProduct.inventory} required /></label><label>Lead time in days<input name="leadTimeDays" type="number" min="1" defaultValue={editingProduct.leadTimeDays} required /></label><label className="check-line"><input name="active" type="checkbox" defaultChecked={editingProduct.active !== false} /> Live in shop</label></div><label>Materials / purchasing needs<textarea name="materials" defaultValue={editingProduct.materials} /></label><label>Customer options · one per line<textarea name="options" defaultValue={editingProduct.options.join("\n")} /></label><button className="add-bag" disabled={saving}>{saving ? "Saving…" : "Update shop →"}</button></form></div>}
    {toast && <button className="ops-toast" onClick={() => setToast("")}>{toast}<span>×</span></button>}
  </main>;
}

function Close({ onClick }: { onClick: () => void }) { return <button type="button" className="modal-close" onClick={onClick}>×</button>; }
function SectionTitle({ title, copy }: { title: string; copy: string }) { return <div className="ops-section-title"><div><h2>{title}</h2><p>{copy}</p></div></div>; }
function Queue({ projects, selected, onSelect, countdown = false }: { projects: StudioProject[]; selected: StudioProject; onSelect: (project: StudioProject) => void; countdown?: boolean }) { return <div className="live-queue"><div className="queue-head"><span>Priority</span><span>Order / project</span><span>Stage</span><span>Payment</span><span>Ship clock</span><span>Progress</span></div>{projects.map((project, index) => { const days = daysUntil(project.due); return <button className={`queue-row ${selected.id === project.id ? "selected" : ""} ${project.priority?.toLowerCase()}`} onClick={() => onSelect(project)} key={project.id}><span className="queue-order">{String(index + 1).padStart(2, "0")}<i>{project.priority ?? "Standard"}</i></span><span className="queue-project"><small>{project.code} · {project.kind}</small><b>{project.name}</b><em>{project.customer}</em></span><span><small>Now</small><b>{project.stage}</b>{project.blocker && <em className="queue-blocker">! {project.blocker}</em>}</span><span><small>Payment</small><b>{project.paymentStatus}</b></span><span className={`ship-clock ${days <= 3 ? "critical" : days <= 7 ? "soon" : ""}`}><strong>{days < 0 ? "Late" : days === 0 ? "Today" : days}</strong><small>{days > 0 ? (days === 1 ? "day" : "days") : ""}</small><em>{project.deliverySpeed}</em></span><span className="queue-progress"><b>{project.progress}%</b><i><em style={{ width: `${project.progress}%` }} /></i>{countdown && <small>{project.remaining} shop hrs left</small>}</span></button>; })}</div>; }
function ProjectDetail({ project, onAdvance, onModal }: { project: StudioProject; onAdvance: (project: StudioProject) => void; onModal: (modal: Modal) => void }) { return <section className="ops-detail"><div className="detail-header"><div><p>{project.code} · {project.customer} · {project.kind}</p><h2>{project.name}</h2></div><span className={`priority-chip ${project.priority?.toLowerCase()}`}>{project.priority}</span></div><div className="project-contact-strip"><span><small>Contact</small><b>{project.customerEmail}</b><em>{project.customerPhone}</em></span><span><small>Ship to</small><b>{project.shippingAddress}</b></span><span><small>Materials</small><b>{project.materialsNeeded}</b></span></div>{project.blocker && <div className="detail-blocker"><b>Blocked</b><span>{project.blocker}</span><button onClick={() => onModal("contact")}>Contact customer →</button></div>}<div className="detail-grid"><article className="next-task"><p>Next shop action</p><h3>{project.next}</h3><div><button className="timer">▶ Start work</button><button onClick={() => onAdvance(project)}>Move to next stage ✓</button></div></article><article><p>Time</p><div className="detail-stat"><strong>{project.remaining}<small>h left</small></strong><span>{project.logged}h logged</span></div><div className="detail-bar"><i style={{ width: `${Math.min(100, project.logged / Math.max(1, project.estimate) * 100)}%` }} /></div></article><article><p>Money</p><div className="detail-stat"><strong>${project.value.toLocaleString()}</strong><span>${(project.value - project.paid).toLocaleString()} owed</span></div><div className="detail-bar money"><i style={{ width: `${project.paid / Math.max(1, project.value) * 100}%` }} /></div></article></div><div className="detail-actions"><button onClick={() => onModal("contact")}>✉ Contact customer</button><button onClick={() => onModal("schedule")}>◫ Adjust schedule</button><button onClick={() => onModal("payment")}>$ Payment / refund</button><button onClick={() => onModal("brief")}>▤ Build design brief</button></div></section>; }
