ALTER TABLE `inquiries` ADD `phone` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `inquiries` ADD `occasion` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `inquiries` ADD `source` text DEFAULT 'gift-finder' NOT NULL;--> statement-breakpoint
ALTER TABLE `inquiries` ADD `image_key` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `inquiries` ADD `image_name` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `inquiries` ADD `object_description` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `inquiries` ADD `dimensions` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `inquiries` ADD `desired_use` text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE `inquiries` ADD `meeting_status` text DEFAULT 'requested' NOT NULL;
--> statement-breakpoint
DELETE FROM `catalog_products`;
--> statement-breakpoint
INSERT INTO `catalog_products` (`slug`,`name`,`category`,`detail`,`price`,`inventory`,`lead_time_days`,`materials`,`options_json`,`image`,`alt`,`badge`,`active`) VALUES
('bourbon-heritage-chest','Bourbon Heritage Chest','Bar & drink','An old-world presentation chest built around a favorite bottle and the story behind it',325,8,14,'Distressed wood chest · fitted hardwood insert · aged hardware','["Bottle and glass layout","Family name or monogram","Interior inscription","Wood tone"]','/assets/toolbox-bourbon-bar.webp','Vintage chest arranged as a bourbon bar','Signature gift',1),
('whiskey-flight-set','Whiskey Flight Set','Bar & drink','Four-glass tasting flight with engraved labels, notes or distillery theme',145,14,8,'Hardwood flight board · tasting glasses','["Wood species","Glass count","Engraving","Gift message"]','/assets/charcuterie-board.webp','Engraved hardwood presentation board','Gift-ready',1),
('shotski','Four-Person Shotski','Bar & drink','Vintage ski, four glasses, school colors and custom engraving',225,12,10,'Vintage ski · four glass holders · engraved hardwood','["College or custom theme","Colors and crest","Names or date","Standard, priority or rush"]','/assets/ski-display.webp','Vintage ski transformed into a custom four-person shotski','College favorite',1),
('beer-caddy','Beer Caddy','Bar & drink','A personalized six-bottle carrier with opener and removable divider',115,16,8,'Hardwood carrier · forged opener · aged hardware','["Six-pack or bomber layout","Name or logo","Finish","Cap catcher"]','/assets/custom-store-display.webp','Custom wood carrier and display','Easy favorite',1),
('opener-cap-catcher','Bottle Opener and Cap Catcher','Bar & drink','Wall-mounted opener with a personalized catch box below',85,20,6,'Hardwood backer · cast opener · catch box','["Name, team or logo","Wood finish","Opener finish"]','/assets/house-sign.webp','Personalized wood wall piece','Fast gift',1),
('coaster-gift-set','Six-Coaster Gift Set','Heritage gifts','Six substantial coasters in a fitted holder with names, maps or marks',78,24,6,'Hardwood, slate or leather · fitted holder','["Material","Set design","Monogram or logo","Gift box"]','/assets/charcuterie-board.webp','Custom engraved hardwood gift set','Under $100',1),
('family-legacy-box','Family Legacy Box','Heritage gifts','A keepsake chest for letters, photographs and the things a family cannot replace',195,10,12,'Solid wood box · aged hardware · lined interior','["Family name","Interior message","Compartments","Wood and finish"]','/assets/toolbox-bourbon-bar.webp','Vintage-style keepsake chest with fitted interior','Heirloom',1),
('mens-valet-box','Men''s Valet Box','Heritage gifts','A clean landing place for a watch, wallet, keys and everyday carry',165,12,10,'Hardwood box · leather or felt lining · aged hardware','["Tray layout","Watch slots","Monogram","Lining color"]','/assets/toolbox-bourbon-bar.webp','Custom fitted wood chest','Personalized',1),
('closing-day-frame','Closing-Day Frame','Home & milestones','A realtor-ready gift for the house photo, address and closing date',125,20,7,'Hardwood frame · engraved address plate','["Photo size","Address and date","Realtor branding","Wood finish"]','/assets/house-sign.webp','Custom engraved home and address piece','Realtor gift',1),
('golf-scorecard-shadow-box','Golf Scorecard Shadow Box','Golf & outdoor','Preserve the scorecard, ball and photograph from the round that mattered',185,10,12,'Hardwood frame · glass · fitted display mounts','["Scorecard size","Ball or tee display","Course name","Plaque engraving"]','/assets/military-plaque.webp','Custom shadow box and commemorative display','Memory keeper',1),
('grilling-set','Personalized Grilling Set','Golf & outdoor','Engraved tools and a purpose-built case for the person who owns the grill',155,14,9,'Stainless tools · fitted wood case','["Tool count","Name or title","Case message","Finish"]','/assets/charcuterie-board.webp','Personalized hardwood presentation set','Host gift',1),
('time-capsule-box','Wedding or New-Home Time-Capsule Box','Home & milestones','A sealed-now, open-later box for vows, letters, photos and first-home memories',225,10,12,'Solid wood chest · aged hardware · interior dividers','["Wedding or new-home edition","Open-on date","Names and coordinates","Interior compartments"]','/assets/toolbox-bourbon-bar.webp','Vintage-style personalized memory chest','Milestone gift',1);
